### ISSUE TITLE
Monitor plugin UI

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#10]
1. Last three buttons Refresh/Save/Mute better looks with class='status' but with diffrent collor for example or more fat border on buttons.

2. There should be border: 1px black solid around the group of hosts and around the title of group it looks much more clear then. (Tree View and Device Template View)

3. The host sholud be more compressed (Default, Tree and Device Template View)

4. In the first list could be position "Text and Time" If You have 100+ hosts it's really hard to view all on a big screen."

**Comment by cigamit** [comment]
Please create a pull request for this.  Simply commenting, though a productive conversation, does not drive change.
