### ISSUE TITLE
Allow lengths of names to be variable to enable full name searching

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#100]
**Is your feature request related to a problem? Please describe.**
1. Cannot search with browser device by part of name if the part is at the end.
2. It doesn't look good when You set maxchars=40.

**Describe the solution you'd like**
Doesn't cut the name after $maxchars=20 just get the other part to next line.

**Describe alternatives you've considered**
Doesn't know how to repair this in other way.

**Comment by netniV** [comment]
I think that would be a preference.  Some people prefer to have the title truncated and then hover over it to see the full detail.

**Comment by interduo** [comment]
Yes, your option is better.

**Comment by cigamit** [comment]
Please attach screen shots.

**Comment by interduo** [comment]
When maxchars = 20,
![maxchars20](https://user-images.githubusercontent.com/17087236/53960744-59385d80-40e7-11e9-89f8-e315b92c41bb.png)

When maxchars = 40,
![maxchars40](https://user-images.githubusercontent.com/17087236/53960745-59385d80-40e7-11e9-946e-504a9e200092.png)

**Comment by cigamit** [comment]
Ugly, but let me think about this.

**Comment by netniV** [comment]
There is where an option to have the name wrap rather than truncate within monitor might be worth exploring.  However, it would make pages longer reducing the number of visible elements in a single glance.

**Comment by k4y53r** [comment]
Hi, 

I'd like it could be set as option on plugin preferences, i use it to monitor isp connections so i prefer it could show full description field (where i set name plus public ip) to get quicker image of failed access.

If i modify maxchar to 40 icons didn't align properly as it happens on version 2.3.5

**Comment by cigamit** [comment]
Can you please test the latest update.  Need some screen shots.

**Comment by netniV** [comment]
Another update will be coming to this shortly as I've just tested this on a medium environment and most views are working well aside from Tiles & Time.

**Comment by netniV** [comment]
I can confirm that this appears to be working.

**Comment by interduo** [comment]
Is there a demo with Cacti  hosted on Your servers?

**Comment by netniV** [comment]
Let me see what I can do...

**Comment by netniV** [comment]
OK, just had a strange experience were it was working but then wasn't...

**Comment by netniV** [comment]
I have made some modifications to allow dynamic selection of the length to 'Trim'.

**Comment by netniV** [comment]
Here is a demonstration of the full effect and covers:

- Initial view with default trimming (refresh shows no change before and after update with the exception of the new Trim setting)
- Full view with no trimming
- Specific view with the number of characters selected

![Jul-15-2019 13-47-15](https://user-images.githubusercontent.com/9052188/61217206-1b87b900-a707-11e9-8a5f-f8989e13e884.gif)
