### ISSUE TITLE
Doubled footer in monitor page (tile view)

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#102]
**Describe the bug**
there is doubled footer in monitor.php
```
All Monitored Devices, and All Criticalities
Remember to first select eligible Devices to be Monitored from the Devices page!
```

**To Reproduce**
1. Go to 'monitor.php'.
2. Scroll down to bottom page.
3. See error

**Expected behavior**
Only one footer.

**Plugin (please complete the following information):**
 - Version: [origin/develop]
 - Source: [github]
 - Identifer: [8dbc777ad65f15518df7c5f741e51254b1545eb4]

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [Chromium]
 - Version [71.0.3578.98]

**Comment by cigamit** [comment]
You need to let us know the exact steps you used to reproduce this.  See if you can re-produce it more than once.  But let us know the precise steps.

**Comment by interduo** [comment]
1. Click on the monitor tab.
2. Choose in filters:
![monitor_filter](https://user-images.githubusercontent.com/17087236/53960593-f0e97c00-40e6-11e9-9704-0eb4d6199506.png)
3. Go to bottom.

**Comment by cigamit** [comment]
Can you please open your browsers debug window and the console and see if you are getting javascript errors.  I can not reproduce using the latest code.

**Comment by netniV** [comment]
I have seen double footers at times.  I'll see if I can replicate it as well tonight.

**Comment by interduo** [comment]
No javascript errors.

**Comment by cigamit** [comment]
This is resolved now.
