### ISSUE TITLE
Host description contains multibyte character set may cause the garbled text

### ISSUE THREAD

**Issue by skyjou** [Cacti/plugin_monitor#105]
**Describe the bug**
Host description contains multibyte character set may cause the garbled text.

**To Reproduce**
1. Give host an description that contains multibyte characters like: 'X9999臺灣分公司-FGT'
2. Click on 'Monitor Page'
3. See the garbled text

**Expected behavior**
It should not show any garbled text.

**Screenshots**
![Screenshot from 2019-03-14 11-18-00](https://user-images.githubusercontent.com/13309854/54329367-622bb080-464c-11e9-8d88-644bfd609aca.png)

**Plugin (please complete the following information):**
 - Version: Latest development version
 - Source: GitHub
 - Identifer: GitHub

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 73

**Comment by netniV** [comment]
Does the correct version should in the database if you select that host?  If not, monitor has no chance.

**Comment by skyjou** [comment]
Yes. This seems cause by the description omit function in monitor page. In the thold page, I can see the correct description of devices.

**Comment by skyjou** [comment]
Hover message of the monitor page shows correct fully description too.

**Comment by netniV** [comment]
OK, I see the reason... it's because of the maximum string length.  It's cutting part of the multi-byte character off.  That's actually more of a core issue since that function comes from the Cacti Core.  If I'm right about that, we will move this to the core repo.

**Comment by netniV** [comment]
Yes it is.  Removing two of the four nines shows a correct character.

**Comment by rtripon** [comment]
Hello,
I'm using this thread, hoping its not a problem, since my problem is somehow similar. After the last pull, I've noticed that hosts with long hostnames are truncated. Is there a way to increase the space between hosts?.
![old pull](https://user-images.githubusercontent.com/28921178/55351002-f65b9b80-54c5-11e9-9aea-64e27b2ea54e.jpg)
![new pull no spaces](https://user-images.githubusercontent.com/28921178/55351010-f9ef2280-54c5-11e9-916d-54e64fd05df2.jpg)

**Comment by cigamit** [comment]
Okay, I've done some commit's, then rolled them back.  Fix needs to be in Cacti.

**Comment by cigamit** [comment]
This is resolved in Cacti 1.2.5.  Closing here.
