### ISSUE TITLE
When mute Time In State wrong 

### ISSUE THREAD

**Issue by walertos86** [Cacti/plugin_monitor#106]
**Describe the bug**
When mute Time In State wrong 

**To Reproduce**
1. Go to monitor
2. Click on mute
5. Time In State change to wrong

**Expected behavior**
When I click to mute Time In State change from 3m down time to 7 days
**Screenshots**
![image](https://user-images.githubusercontent.com/48942426/54979622-50330180-4fac-11e9-852b-cb13ce7d0593.png)
![image](https://user-images.githubusercontent.com/48942426/54979656-6476fe80-4fac-11e9-8a22-354afe9b5370.png)

**Plugin (please complete the following information):**
- Version: [git]
- Version of Cacti 1.2.2
- Source: [github]
- Identifer: [orgin/develop, updated dialy]

**Desktop (please complete the following information):**
 - Device: PC
 - OS: Win 10
 - Browser Chrome

**Comment by cigamit** [comment]
Well, that is odd.  I'll need the host record from you database the next time this happens.  You can dump your host table and forward to developers at cacti dot net.  Thanks.

**Comment by walertos86** [comment]
Error in /cacti/lib/functions.php
`} elseif ($host['status_event_count'] > 0 && ($host['status'] == 1 || $host['status'] == 2)) {`

`} elseif ($host['status_event_count'] > 0 && ($host['status'] == 1 || $host['status'] == 2 || $host['status'] == 5)) {`

**Comment by netniV** [comment]
For reference, this was added in https://github.com/Cacti/cacti/commit/0c9a29cf3 as reported in https://github.com/Cacti/cacti/pull/3601
