### ISSUE TITLE
Extraneous and misleading notification 

### ISSUE THREAD

**Issue by Lalbee99** [Cacti/plugin_monitor#107]
**Describe the bug**
Anytime a host reboots or the host's snmpd daemon is restarted an email is sent correctly stating the host is either down or restarted but a page is sent to the pager that reads  "Cacti Monitor Plugin requires an html based Email client". The notification list contains and email as well as the pager.  

**To Reproduce**
1. Reboot host or restart snmpd on the host 

**Expected behavior**
Notification that the host is either down or up . 

**Screenshots**

**Plugin (please complete the following information):**
 - Version: [2.3.4]
 - Source: [github]
 - Identifer: [github commit ref]

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Mozilla]
 - Version []

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lalbee99** [comment]
It seems that the monitor's default format is sending something other than plain text to the pager causing the message to be sent.

**Comment by Lalbee99** [comment]
I looked in the formats directory and all formats are sending HTML. This causes problems when attempting to page out on pagers "Cacti Monitor Plugin requires an html based Email client"

**Comment by Lalbee99** [comment]
bump

**Comment by Lalbee99** [comment]
Since there doesn't appear to be any interest to fix this , Can I use a "poller_monitor.php" from a pre-broken  version of monitor.

**Comment by cigamit** [comment]
As a work around, install Thold if its not installed, and turn on the option for "Text Only Emails".  Thold will no longer send HTML emails though, so you will lose that.  If you can't lose that, then toggle the "html = true" at 
https://github.com/Cacti/plugin_monitor/blob/develop/poller_monitor.php#L595

A long term fix for this would be to change the notification lists themselves to specify whether they would want HTML or TXT.  We also need to decouple the monitor and thold settings completely.

On a side note, I find it funny that people still use pagers in this day and age. :)

**Comment by Lalbee99** [comment]
Jimmy thanks for the suggestion but I already had THOLD installed (1.2.4) and "Send Alerts as Text" was already ticked to the right to enable. This appears to be a bug. The email will come through but the pager message will read "Cacti Monitor Plugin requires an html based Email client". When I was running on older versions of Cacti (0.8.7, 0.8.8 etc..) This was not a problem.

**Comment by Lalbee99** [comment]
By the way not my choice on using the pagers LOL!

**Comment by Lalbee99** [comment]
Performing more troubleshooting and placed some debugging statements in poller_monitor.php. Even though I have "Send alerts as text" it appears $output gets wrapped in css & html amy ways
DEBUG "error variable:       Status variable: Reboot Notifications  output variable: <html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
</head>
<body>
<style type='text/css'>

body {
margin-left: auto;
margin-right: auto;
background-color: snow;
}

table {
border-collapse: collapse;
border-spacing: 0;
border: none;
text-align: center;
align-content: center;
width: 100%;
}

.report_table {
background-color: #F9F9F9;
text-align: center;
border: 0;
width: 100%;
border: 3px outset #CCCCCC;
padding: 4px;
margin: auto;
}

.title_row {
background-color: #EAEAEA;
border: 2px double #CCCCCC;
padding: 3px;
}

.title {
background-color: #EAEAEA;
font-size: 16pt;
text-align: left;
border: 2px double #CCCCCC;
padding: 3px;
}

.image_table {
margin-left: auto;
margin-right: auto;
width: 100%;
}

.image_row {
}

.image_column {
text-align: center;
}

.image {
}

.text_row {
background-color: #EAEAEA;
}

.text {
background-color: #EAEAEA;
font-size: 16pt;
text-align: left;
border: 1px solid #CCCCCC;
padding: 0px;

}

.header_table {
background-color: #3F750F;
text-align: center;
width: 100%;
border: 3px ridge #3F750F;
padding: 4px;
margin: auto;
}

.header_row {
background-color: #3F750F;
}

.header {
background-color: #3F750F;
font-size: 16pt;
text-align: left;
color: #FFF;
}

.left {
text-align: left;
}

.right {
text-align: right;
}

.center {
text-align: center;
}

.footer {
background-color: #3F750F;
font-size: 10pt;
text-align: left;
color: #FFF;
}

</style>
<table class='header_table'>
<tr class='header_row' ><td class='header'>Cacti Reporting Report</td></tr>
<tr><td>
<h1>Monitor Reboot Notification</h1><p>The following Device's were Rebooted or SNMP was restarted.  See details below for additional information.</p><br><table class="report_table">
<tr class="header_row">
<th class="left">Description</th><th class="left">Hostname</th>
</tr>
<tr><td class="left">XXXXXXXXXXX</td><td class="left">XXXXXXXXXXX.XXXXX.XXX</td></tr>
</table>

</td></tr>
<tr class='header_row'><td class='footer'>Copyright &copy; 2004-2019 - <a href="http://www.cacti.net">The Cacti Group</a></td></tr>
</table>
</body>
</html>
"

**Comment by cigamit** [comment]
I just did a code review of the latest develop version of monitor, and I found no such instance of the "Cacti Plugin Monitor requires an" anywhere.  Are you sure you are using the latest develop version?  The thold text email setting should work as expected.

**Comment by netniV** [comment]
Ensure you are on the latest version of monitor as the older versions showed the above text and didn't properly support non-HTML.  I updated from a6b587d to f07bb91 and noticed the changes had been implemented since December and is why @cigamit failed to find the "Cacti Monitor Plugin requires an html based Email client" text.
