### ISSUE TITLE
Cacti : Not compatible, Legacy plugin

### ISSUE THREAD

**Issue by renaldi98** [Cacti/plugin_monitor#110]
Can i get an answer, for the finishing my project.

Plugin name:
Mikrotik
Monitor
Thold
Status:
Not Compatible, Legacy plugin.

I try all maybe but still not work.

**Comment by renaldi98** [comment]
https://github.com/Cacti/plugin_monitor

i try it but maybe can i get a tgz version? or anything help for my problme thanks.

**Comment by netniV** [comment]
If you haveCacti 0.8 you need the older plugins.  If you have 1.x or above, you need at least the highest version listed in the INFO files for the plugins.

**Comment by netniV** [comment]
Oh and you need the plugins from the releases section of GitHub repos for each plugin

**Comment by renaldi98** [comment]
cacti already install plugins Mikrotik,Monitor and Thold. and im trying to install with your step or maybe my step is wrong can i get a correctly tutor for that installation?? 

i done to wget and git clone https://github.com/Cacti/plugin_monitor.git but after that im stuck and the plugin still not compatible

**Comment by renaldi98** [comment]
for the spesification my installation.
my cacti version is 1x 
im going to cd /usr/share/cacti
and wget https://github.com/Cacti/plugin_monitor.git
then i get notif plugin_monitor.git already save
then what i do? use tar xzf ...? but not work for me hehe 

so i try other step before that im already install yum install git
next cd /usr/share/cacti
and git clone https://github.com/Cacti/plugin_monitor.git
then notif like successfully but what's next?


Done, problem solve.
