### ISSUE TITLE
Monitor cacti : The cacti poller has not run yet || And Dataquery is empty

### ISSUE THREAD

**Issue by renaldi98** [Cacti/plugin_monitor#112]
Can you are help me... because after i done installation plugin monitor and create a device to monitoring. but after that i open tab monitor and then click the device and then trala 

'The cacti poller has not run yet' 

before the problem i get some fail step? for the data query is not fill anything. but in video tutor youtube the data is fill and too much

**Comment by netniV** [comment]
That means that you have not created the cron job to run the poller.  All that is explained in the documentation.  For setup issue, the forums are your best bet.  We tend to use GitHub only for tracking issues.
