### ISSUE TITLE
Location in UI in default view

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#115]
**Is your feature request related to a problem? Please describe.**
Yes - when there is downed device firstly You need to know where device is located. Now You have to check that in other modules of Cacti. Time matters.

**Describe the solution you'd like**
1. Infromation in popup (Device status information) about location.
2. Information under the downtime about location:
- only when grouping = default(none),
- only when device is down,
- obviously only when there is more than one location,

**Comment by netniV** [comment]
Please be clear about what 'location' you mean?  Are you referring to the site, syslocation or something else?

**Comment by interduo** [comment]
Location in Cacti means Site whitch od set by user when adding a Device.

**Comment by TheWitness** [comment]
This will be in 2.6 release
