### ISSUE TITLE
Feature Request Add node name to reboot notifications

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_monitor#119]
Hey Guys 

One thing that would be nice would be having the node name in the subject line of the reboot notification 

This is nice for integration into ticketing systems like Service now the info in the subject line to open a ticket 

Thanks!

**Comment by interduo** [comment]
What to include in subject when rebooted nodes was more than one?

**Comment by bmfmancini** [comment]
To be honest I want to move away from email all together so far all plugins that we use Thold,syslog etc all support the send a command function so we send a curl request to our ticketing system without having to parse emails 

Monitor is the only plugin missing this feature  which would be nice for up/down and reboot events I have put in a feature request here but nothing so far

I am not sure what could be sent in the subject for multiple devices through unless it multiple emails being sent per device then it would be the hostname in the subject

**Comment by interduo** [comment]
Email message per device reboot is a good idea for me also.

**Comment by TheWitness** [comment]
Closing.  Please re-open with a specific request.

**Comment by interduo** [comment]
@TheWitness it would be good to:
- send one notification when node reboots per host,
- include node name in notification subject,

I got no privileges for reopening.
