### ISSUE TITLE
Cacti Device Reboot Notification - don't include hosts with no monitor device set

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#122]
In **Cacti Device Reboot Notification** - don't check hosts with no `[x] monitor device` in device setting and don't send raport for them.

In my opinion this is bug but somebody could said this is not bug.

**Comment by netniV** [comment]
I have often considered the same thing but I think whether or not you create a threshold for a device, the monitoring attribute applies to both Monitor and Thold.
