### ISSUE TITLE
SQL Errors when removing hosts that no longer exist

### ISSUE THREAD

**Issue by angelsu00** [Cacti/plugin_monitor#124]
when I upgrade 1.2.7 to 1.2.8 got an error
mysql version 5.6.46

CMDPHP SQL Backtrace: (/plugins/monitor/poller_monitor.php[87]:monitor_uptime_checker(), /plugins/monitor/poller_monitor.php[185]:db_execute(), /lib/database.php[191]:db_execute_prepared())
CMDPHP ERROR: A DB Exec Failed!, Error: You can't specify target table 'plugin_monitor_uptime' for update in FROM clause

**Comment by Lalbee99** [comment]
No resolution? This issue was opened 8 months ago.

**Comment by Lalbee99** [comment]
No resolution? This issue was opened 8 months ago.

**Comment by Lalbee99** [comment]
No resolution? This issue was opened 8 months ago.

**Comment by Lalbee99** [comment]
No resolution? This issue was opened 8 months ago.

**Comment by Lalbee99** [comment]
No resolution? This issue was opened 8 months ago.

**Comment by Lalbee99** [comment]
No resolution? This issue was opened 8 months ago.

**Comment by Lalbee99** [comment]
No resolution? This issue was opened 8 months ago.

**Comment by Lalbee99** [comment]
No resolution? This issue was opened 8 months ago.

**Comment by Lalbee99** [comment]
No resolution? This issue was opened 8 months ago.

**Comment by Lalbee99** [comment]
No resolution? This issue was opened 8 months ago.
