### ISSUE TITLE
Limit the amount of devices shown

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_monitor#127]
Hey Everyone 

On Large installs, the monitor plugin can be slow to pull all devices/trees
It would be nice to be able to limit the devices per page say 500 per page or something

Or have the option not to display any devices at all unless you search for them ????

**Comment by netniV** [comment]
I disagree with the 'do not search' option as the whole point of monitor is to sit there and be seen.  Also, it can be the same with Paging, people might miss things that are important.

But I agree there needs to be a trade off when you have larger systems, as it increase the time for each that it queries.

**Comment by TheWitness** [comment]
This one was fixed.  Limit is 30 and static.
