### ISSUE TITLE
SQL errors happen during Autom8 runs Monitor 2.3.6

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_monitor#128]
hey All 

I have noticed that on 1.2.9 monitor generates the following errors while adding new devices 

2020/03/30 15:28:54 - CMDPHP SQL Backtrace: (/plugins/monitor/poller_monitor.php[87]:monitor_uptime_checker(), /plugins/monitor/poller_monitor.php[200]:db_execute(), /lib/database.php[210]:db_execute_prepared())
2020/03/30 15:28:54 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'plugin_monitor_reboot_history' is specified twice, both as a target for 'DELETE' and as a separate source for data
2020/03/30 15:28:54 - CMDPHP SQL Backtrace: (/plugins/monitor/poller_monitor.php[87]:monitor_uptime_checker(), /plugins/monitor/poller_monitor.php[185]:db_execute(), /lib/database.php[210]:db_execute_prepared())
2020/03/30 15:28:54 - CMDPHP ERROR: A DB Exec Failed!, Error: Table 'plugin_monitor_uptime' is specified twice, both as a target for 'DELETE' and as a separate source for data

The plugin otherwise works fine just some odd behavior 
I am wondering if it has to do with the recent changes made to autom8 

this is on monitor version 2.3.6

**Comment by TheWitness** [comment]
This was fixed a long time ago.  I'll drop it into the 2.6 changelog.
