### ISSUE TITLE
Modifications to automate settings should be disabled when scan is running

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_monitor#133]
Hey Everyone 

I am getting tons of the below errors all of a sudden  everything seems to be working fine
cacti version 1.2.5 

2019/07/31  20:14:45 - CMDPHP PHP ERROR NOTICE Backtrace:   (/poller_automation.php[354]:discoverDevices(),  /poller_automation.php[530]:CactiErrorHandler())
--
2019/07/31 20:14:45 - ERROR PHP NOTICE: Undefined index:  ping_timeout in file: /var/www/html/cacti/poller_automation.php  on  line: 530
2019/07/31 20:14:45 - CMDPHP PHP ERROR NOTICE Backtrace:   (/poller_automation.php[354]:discoverDevices(),  /poller_automation.php[530]:CactiErrorHandler())
2019/07/31 20:14:45 - ERROR PHP NOTICE: Undefined index: ping_method  in file: /var/www/html/cacti/poller_automation.php  on line: 530
2019/07/31 20:14:45 - CMDPHP PHP ERROR NOTICE Backtrace:   (/poller_automation.php[354]:discoverDevices(),  /poller_automation.php[527]:CactiErrorHandler())
2019/07/31 20:14:45 - ERROR PHP NOTICE: Undefined index: ping_port  in file: /var/www/html/cacti/poller_automation.php  on line: 527
2019/07/31 20:14:45 - CMDPHP PHP ERROR NOTICE Backtrace:   (/poller_automation.php[354]:discoverDevices(),  /poller_automation.php[526]:CactiErrorHandler())
2019/07/31 20:14:45 - ERROR PHP NOTICE: Undefined index:  ping_retries in file: /var/www/html/cacti/poller_automation.php  on  line: 526
2019/07/31 20:14:45 - CMDPHP PHP ERROR NOTICE Backtrace:   (/poller_automation.php[354]:discoverDevices(),  /poller_automation.php[500]:CactiErrorHandler())
2019/07/31 20:14:45 - ERROR PHP NOTICE: Undefined index: site_id in  file: /var/www/html/cacti/poller_automation.php  on line: 500
2019/07/31 20:14:45 - CMDPHP PHP ERROR NOTICE Backtrace:   (/poller_automation.php[354]:discoverDevices(),  /poller_automation.php[499]:CactiErrorHandler())
2019/07/31 20:14:45 - ERROR PHP NOTICE: Undefined index: poller_id  in file: /var/www/html/cacti/poller_automation.php  on line: 499
2019/07/31 20:14:45 - CMDPHP PHP ERROR NOTICE Backtrace:   (/poller_automation.php[354]:discoverDevices(),  /poller_automation.php[498]:CactiErrorHandler())
2019/07/31 20:14:45 - ERROR PHP NOTICE: Undefined index: snmp_id in  file: /var/www/html/cacti/poller_automation.php  on line: 498
2019/07/31 20:14:45 - CMDPHP PHP ERROR NOTICE Backtrace:   (/poller_automation.php[354]:discoverDevices(),  /poller_automation.php[453]:CactiErrorHandler())
2019/07/31 20:14:45 - ERROR PHP NOTICE: Undefined index:  enable_netbios in file: /var/www/html/cacti/poller_automation.php  on  line: 453
2019/07/31 20:14:45 - CMDPHP PHP ERROR NOTICE Backtrace:   (/poller_automation.php[354]:discoverDevices(),  /poller_automation.php[530]:CactiErrorHandler())
2019/07/31 20:14:45 - ERROR PHP NOTICE: Undefined index:  ping_timeout in file: /var/www/html/cacti/poller_automation.php  on  line: 530

Date | Wed, 31 Jul 2019 20:19:59 -0400
-- | --
Cacti Version | 1.2.5
Cacti OS | unix
RSA Fingerprint | 5f:c6:e7:c5:42:82:af:57:cb:65:cf:fb:38:d7:67:51
NET-SNMP Version | NET-SNMP version: 5.7.2
RRDtool Version Configured | 1.4.0+
RRDtool Version Found | 1.4.8
Devices | 22
Graphs | 128
Data Sources | Script/Command: 14SNMP Get: 15SNMP Query: 43Script Server: 55Total: 127

I have 2 Pollers in this setup this is my lab earlier today I did a fail test on the secondary poller for testing and thats around the time the errors started coming In I disabled all other plugins still the same 

Errors are coming in really fast too

Any ideas or help would be great !
thanks in advanced !

**Comment by bmfmancini** [comment]
@edewillians10  be careful when posting the full output of the sql command you just posted your SNMP string, IP, and hostname unless of course, this is a test box or something 

@TheWitness  Yes I reported something similar to this last week on the monitor tab @netniV was working on that 
I think this is related! 

In my case using Monitor 2.6 and I've seen it even on fresh installs

**Comment by edewillians10** [comment]
Thank you so much guys.

Yes, this is a VM in my PC... no issue publishing those IPs, all of them are local.

**Comment by TheWitness** [comment]
Too much going on here.  Marking this duplicate the default null column issue will be resolved in 2.6.
