### ISSUE TITLE
WEBUI WARNING: Attempt to use GET method for POST operations

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_monitor#139]
Cacti 1.2.17 & Monitor 2.5
```
2021/01/21 14:12:43 - WEBUI WARNING: Attempt to use GET method for POST operations from IP x.x.x.x
```

Go to monitor tab and click save on the monitor filter

**Comment by netniV** [comment]
That happens if the action is a 'save', 'update_data' or 'changepassword' without a CSRF magic token.

**Comment by netniV** [comment]
https://github.com/Cacti/cacti/blob/ff317977212c94feeceff14b5dae698bbeb2bf5d/include/global.php#L554

**Comment by TheWitness** [comment]
I'm guessing that monitor needs to be updated to use post.

**Comment by TheWitness** [comment]
I've fixed this now.
