### ISSUE TITLE
Spelling Error in Reboot Email Subject

### ISSUE THREAD

**Issue by mrjackson** [Cacti/plugin_monitor#140]
**Describe the bug**
Notification is misspelled in the subject of the reboot email

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Monitor Tab'
3. Scroll down to 'Reboot Notifications'
4. See spelling error "Nofication" in Subject line

**Expected behavior**
Should be spelled Nofication

**Plugin (please complete the following information):**
 - Version: 2.3.4 and 2.5
 - Source: github

**Additional context**
setup.php lines 603 and 605

**Comment by TheWitness** [comment]
Thanks for reporting.  Fixed.
