### ISSUE TITLE
Limit device view based on User Permission Settings

### ISSUE THREAD

**Issue by fzlrhm29** [Cacti/plugin_monitor#143]
Hi, 

Can we limit a user's view in Monitor to only see devices that have been granted to them in Cacti User Permission Settings (device/tree)?

I have restricted the user to only view devices in a specific Tree (Users->Tree Permission) but the user seems to be able to view all devices in Monitor.

Appreciate your help

Thanks.

![image](https://user-images.githubusercontent.com/85541298/121847606-69eec980-cd1b-11eb-873e-d91c8405a777.png)

**Comment by netniV** [comment]
Are you sure that they haven't been allowed permissions at a group level?

**Comment by fzlrhm29** [comment]
Do you mean to restrict the permission at User Groups level?

Yes, I have set following policy in the User Group (graph permission method is Restrictive):
Graph: Allow | Device: Deny | Template: Deny | Tree: only allow one Tree 

But I can still see all other devices that is not inside that specific tree group in Monitor.


![Screenshot 2021-06-15 132639](https://user-images.githubusercontent.com/85541298/121997789-7f2c2c80-cddd-11eb-8aff-e2d5a63de553.jpg)

![Screenshot 2021-06-15 132539](https://user-images.githubusercontent.com/85541298/121997808-881cfe00-cddd-11eb-8bb8-89e230698f3b.jpg)

> Are you sure that they haven't been allowed permissions at a group level?

**Comment by TheWitness** [comment]
The code looks good, though I'm going to change it slightly.  Keep in mind if a user has access to a single graph on a device, they have access to see the device.
