### ISSUE TITLE
Monitor Plugin Last fail date always update to 1970

### ISSUE THREAD

**Issue by nghost-nghost** [Cacti/plugin_monitor#148]
Hi
I'm using cacti 1.2.19 and monitor plugin 2.5 on ubuntu 20.04
i have problem when device down, the time of last fail is correct. but after a second its updated to 1970-01-01
how to fix this?

![image](https://user-images.githubusercontent.com/100486788/161456784-ac8d3bed-4375-4c58-a84f-e987e0e7892d.png)

**Comment by TheWitness** [comment]
Oh, interesting.  We might have to re-pull that function from Cacti, or just use the Cacti function.

**Comment by netniV** [comment]
It may also be happening if your mySQL is not set to allow zero dates.

**Comment by Kodlitko** [comment]
Hello, I am facing same issue on my instance - all hosts have last fail date 1970-01-01 01:32:50.

Can you please tell me, what exact MySQL options should I search for? Thanks.

My system:
Debian Linux 10
MariaDB v10.3.34
PHP v7.3.31
Cacti v1.2.22
Monitor plugin v2.5

**Comment by CatGuai** [comment]
ran into the same problem
AlmaLinux 8.6

**Comment by TheWitness** [comment]
That 1970 date is old school never seen.  @netniV may be right.

**Comment by netniV** [comment]
I think we may have to start revisiting the idea of using null dates rather than zero dates @TheWitness as much as it pains us

**Comment by TheWitness** [comment]
Resolved.
