### ISSUE TITLE
 PLUGIN WARNING: Plugin hook 'monitor_device_action_prepare' from Plugin 'monitor' must return the calling array or variable, and it is not doing so. Please report this to the Plugin author. 

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_monitor#154]
When I change the monitoring level of some device, I got this warning.

And it's on 
Cacti 1.2.22
 Thold:1.2.1
Monitor 2.5

**Comment by arno-st** [comment]
Line 348 in setup.php int the develop branch
but 303 in the master branch

missing:
return $save;

**Comment by TheWitness** [comment]
Grab the latest setup.php.  Should be fixed now.
