### ISSUE TITLE
"Check red fields" error on Cacti 1.2.x

### ISSUE THREAD

**Issue by stslayer1** [Cacti/plugin_monitor#156]
**Describe the bug**

After updating Cacti to version 1.2.21, there was a problem with the Monitor plugin.

"Sorry, we could not process your last action. Save Failed due to field input errors (Check red fields)." error pops up randomly.

Screenshot: https://prnt.sc/FDpjpenCzVnV

**To Reproduce**
1. Go to 'Monitor'
2. Click on 'Graphs'
3. See error

**Plugin Monitor:**
 - Version: 2.5
 - Source: https://github.com/Cacti/plugin_monitor/releases/tag/v2.5

I also tried a clean install of version 1.2.23, but when installing the Monitor plugin, the error also appears.

**Comment by linqianye** [comment]
I also encountered the same problem, how to deal with it?

**Comment by TheWitness** [comment]
Do you both have cacti up in more than one window when it happens?

**Comment by TheWitness** [comment]
You'll have to find a repeatable case in any event.

**Comment by linqianye** [comment]
I have found a solution. Using the latest development version can avoid this error. It seems that the development version has fixed this problem.

**Comment by TheWitness** [comment]
Good

**Comment by stslayer1** [comment]
> 

Latest dev. version of Cacti or Monitor plugin?

**Comment by TheWitness** [comment]
If you are running an 8.x version of PHP or even a recent 7.4 version, best to update both.  Cacti 1.2.x branch is pretty much set for 1.2.24.  I'm running in prod with it.

**Comment by linqianye** [comment]
> 
the development version of the monitor plugin

**Comment by chrcoluk** [comment]
I hit this problem as well, didnt show up until php was upgraded to 8.0, fixed on the dev branch.
