### ISSUE TITLE
UI Improvement: Black Border and floating

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#16]
```
@@ -845,7 +851,7 @@ function render_tree() {
                                FROM host AS h
                                WHERE id IN (" . implode(',', $host_ids) . ")");
 
-                       $result .= '<div style="padding:2px;margin:2px;width:100%;"><table class="odd" style="width:100%;"><tr class="tableHeader"><th>Non Tree Devices</th></tr><tr><td><div style="width:100%">';
+                       $result .= '<div style="padding:2px;margin:2px;width:100%;"><table class="odd" style="width:100%; border: 1px black solid;"><tr class="tableHeader" style="border: 1px black solid;"><th>Non Tree Devices</th></tr><tr><td><div style="width:100%">';
                        foreach($hosts as $leaf) {
                                $result .= render_host($leaf, true, $maxlen);
                        }
```

```
@@ -813,13 +819,13 @@ function render_tree() {
                                                if ($ptree != '') {
                                                        $result .= '</div></td></tr></table></div>';
                                                }
-                                               $result .= '<div style="padding:3px;margin:4px;width:100%;"><table class="odd" style="width:100%;margin-left:auto;margin-right:auto;"><tr class="tableHeader"><th>' . $tree_name . '</th></tr><tr><td><div style="width:100%">';
+                                               $result .= '<div style="padding:3px;margin:3px;width:100%;"><table class="odd" style="border: 1px black solid;width:100%;margin-left:auto;margin-right:auto;"><tr class="tableHeader"><th>' . $tree_name . '</th></tr><tr><td><div style="width:100%">';
                                                $ptree = $tree_name;
                                        }
 
                                        $title = $title !='' ? $title:'Root Folder';
 
-                                       $result .= '<div style="vertical-align:top;float:left;position:relative;height:' . intval(get_request_var('size') + 52) . 'px;padding:3px;margin:4px;white-space:nowrap;"><table class="odd"><tr class="tableHeader"><th>' . $title . '</th></tr><tr><td class="center"><div>';
+                                       $result .= '<div style="vertical-align:top;float:left;position:relative;height:float;padding:3px;margin:3px;white-space:nowrap;"><table class="odd" style="border: 1px black solid;"><tr class="tableHeader"><th>' . $title . '</th></tr><tr><td class="center"><div>';
                                        foreach($hosts as $host) {
                                                $result .= render_host($host, true, $maxlen);
                                        }


```

Please update the code.

- Black border is much more visible.
- Groups aren't overlapping by each other if group has many hosts.

**Comment by cigamit** [comment]
What I'll have to do here is generate a theme based css file so that people can make it what they want it to be.  The first mistake of this was to place so much inline styles onto the page.  It's was a mistake.  This will get resolved sometime after release of Cacti 1.0

**Comment by interduo** [comment]
With overlapping the monitor plugin is useless in some parts. If You use it to find hosts and click it...

OK - but for now You can just update this few charts...You've got diff working and tested.
Not much work at all.

You are right.

**Comment by cigamit** [comment]
Please attach screen shots before an after please.

**Comment by interduo** [comment]
Look at overlapping at one nohidden name of netnode. It's obviously bug not "make it what they want it to be."

![cacti_after](https://cloud.githubusercontent.com/assets/17087236/22157988/5a1c927c-df3a-11e6-9a21-af7c77f2a67f.png)
![cacti_before](https://cloud.githubusercontent.com/assets/17087236/22157989/5a42728a-df3a-11e6-9fed-c1f12a27fb7f.png)

**Comment by cigamit** [comment]
Yea, I see what you mean.

**Comment by cigamit** [comment]
Is that snmp issue resolved now?

**Comment by interduo** [comment]
SNMP issue resolved. 
Thanks.

Will You update the code?

**Comment by interduo** [comment]
What SNMP issue?
Do You mean https://github.com/Cacti/cacti/issues/224 ?

**Comment by interduo** [comment]
Will You update the code with those things?

**Comment by interduo** [comment]
Will You update the code with those things?

**Comment by cigamit** [comment]
I'm still focused on core bugs.  This requires re-plumbing to allow for theme based CSS.  What was done initially did not follow our guideline of no inline styles.

**Comment by cigamit** [comment]
Monitor 2.1 has been released which is CSS based.  Please review the your output using the new interface and modify the CSS files per your liking and open a pull request once you have made your adjustments.  Thanks!

**Comment by interduo** [comment]
This is not resolved properly.

I know that CSS positioning is obviously required but this issue is not resolved in git.
The overlapping in icons exists.

**Comment by cigamit** [comment]
Yea, I was thinking of this over night, need to move more into CSS as there are still some inline styles.

**Comment by cigamit** [comment]
Okay, I've moved more to classes.  This should be working well now.  Please create a pull request for your additional CSS modifications.  It should be strait forward now.  Note, you will have to reset your 'size' and save.
