### ISSUE TITLE
Device criticality, and other options not saved.

### ISSUE THREAD

**Issue by dallenk** [Cacti/plugin_monitor#160]
**Describe the bug**
when editing a device, setting any option other than "Monitor Device" is not saved.  No errors in the log, user is returned to the edit device page.

**To Reproduce**
1. Edit a device
2. Set "Criticallity"
3. set any other options
4. save

![image](https://github.com/Cacti/plugin_monitor/assets/2725066/81c0f00a-d734-4ce4-9382-2e7f71901d57)

**Comment by xmacan** [comment]
Cannot reproduce this. What monitor plugin version? I suggest use actual develop branch

**Comment by dallenk** [comment]
interesting, I can't reproduce this since I had the issue.. but have always run the most current pull develop branches.

Will close for now.  thanks!
