### ISSUE TITLE
Table name is wrong ALTER TABLE plugin_monitor_update should be ALTER TABLE plugin_monitor_uptime

### ISSUE THREAD

**Issue by MSS970** [Cacti/plugin_monitor#162]
https://github.com/Cacti/plugin_monitor/blob/396fa1da897127a2d45e78be107757c6d7be9ed5/setup.php#L190

Issue: table name is wrong:

		db_execute('ALTER TABLE plugin_monitor_update
			MODIFY COLUMN uptime BIGINT unsigned NOT NULL default "0"');

It should be:

		db_execute('ALTER TABLE plugin_monitor_uptime
			MODIFY COLUMN uptime BIGINT unsigned NOT NULL default "0"');

**Comment by xmacan** [comment]
Thank you for reporting. Fix #164
