### ISSUE TITLE
small visual bug in tree view

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#173]
**Describe the bug**
In monitor plugin in "Site" view the icons are not positioned by top line as on screenshot.

**To Reproduce**
1. Go to https://cacti/plugins/monitor/monitor.php?action=change&refresh=30&grouping=tree
2. See results

**Expected behavior**
Icons in one line.

**Screenshots**
![image](https://github.com/Cacti/plugin_monitor/assets/17087236/9949209d-08e0-46fa-bcdc-0715b7834971)

**Comment by TheWitness** [comment]
@xmacan, can you look at this?  Maybe a w3c violation or muddled up CSS classes.

**Comment by TheWitness** [comment]
I'm not seeing this on the 1.2.x branch.  Maybe you modified your main.css file a bit?

![image](https://github.com/Cacti/plugin_monitor/assets/1439914/21b6d77b-b949-49ed-a47a-069c84445609)

**Comment by interduo** [comment]
@TheWitness you have got all device names very short. It occurs when device names are mixed (short and long).
I tested on origin/develop branch and 1.2.x

**Comment by xmacan** [comment]
I will look at it

**Comment by xmacan** [comment]
@interduo - one word change. Please could you test?

**Comment by interduo** [comment]
It's ok now - but only when icons are set to medium. You need to put this change also in other CSS classes.

**Comment by xmacan** [comment]
You are right, fixed, thank you

**Comment by interduo** [comment]
Please close issue when You merge this commit(s). Thanks.
