### ISSUE TITLE
Issue with mute function

### ISSUE THREAD

**Issue by dmeshalkin** [Cacti/plugin_monitor#175]
Hello!
We are using a monitor plugin and encountered the following issue. We have a problem with the mute button functionality. When one of the devices is in a down state and the mute button is used, if any other device go to the down state, the sound does not reappear, and the devices remain in a Down (muted/acked) state.
Cacti version | 1.2.26
Thold | 1.8
Monitor | 2.6

Thank you for your attention.

**Comment by dmeshalkin** [comment]
upd: after few experiments we understood, this issue is only when update monitor interval is 1 minute. If update interval 10 seconds all works pretty good.

**Comment by TheWitness** [comment]
Do a test with the Browsers debug window open on the Console and see if there is a JavaScript error when you have it muted and take down another device.  If you get a JavaScript error, post your browser type and version and the JavaScript error.  Are you using the latest Develop branch?

**Comment by TheWitness** [comment]
I'm just confirming this.

**Comment by TheWitness** [comment]
I backed off to pre-2024, and the device starts to show down, and it attempts to make noise, but look at this new feature...

![image](https://github.com/Cacti/plugin_monitor/assets/1439914/27d2b0ed-fa33-44bd-aca9-0c79a08cc9a9)

@xmacan, I think you broke this.  I'll take a look at fixing it.  I noted something wrong in the Pull Request, but just let it in.  I'll get it fixed.

**Comment by xmacan** [comment]
sorry about that. I assume it was when adding different icons to devices, but I don't see where I broke it.

**Comment by TheWitness** [comment]
This is a new browser security thingy.  I'm working on it this morning.  Already made one commit here: 4ba12e8cc81d142d5bbd6eabe8cf7e1117ad3969

**Comment by TheWitness** [comment]
![image](https://github.com/Cacti/plugin_monitor/assets/1439914/f25bbc11-c7d9-4ccf-bd57-03f46fa4cd3a)

Works again from my perspective.  First Order makes it awesome with the spinning icon 👍
