### ISSUE TITLE
Fresh install - PHP Error

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_monitor#18]
Hi there,

I'm just testing Cacti 1.0.0 and plugins to migrate my current installation in the near future.

Plugin installation went well but I see these errors on cacti's log

> 2017-02-07 11:17:42 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/monitor/monitor.php: 87 ajax_status)(/plugins/monitor/monitor.php: 1077 CactiErrorHandler)(/lib/functions.php: 4230 cacti_debug_backtrace)
> 2017-02-07 11:17:42 - ERROR PHP NOTICE in Plugin 'monitor': Undefined index: 0 in file: /var/www/html/cacti-1.0.0/plugins/monitor/monitor.php on line: 1077
> 2017-02-07 11:17:42 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/monitor/monitor.php: 87 ajax_status)(/plugins/monitor/monitor.php: 1076 CactiErrorHandler)(/lib/functions.php: 4230 cacti_debug_backtrace)
> 2017-02-07 11:17:42 - ERROR PHP NOTICE in Plugin 'monitor': Undefined index: 0 in file: /var/www/html/cacti-1.0.0/plugins/monitor/monitor.php on line: 1076
> 2017-02-07 11:17:39 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/monitor/monitor.php: 101 draw_page)(/plugins/monitor/monitor.php: 121 render_default)(/plugins/monitor/monitor.php: 641 render_host)(/plugins/monitor/monitor.php: 935 CactiErrorHandler)(/lib/functions.php: 4230 cacti_debug_backtrace)
> 2017-02-07 11:17:39 - ERROR PHP NOTICE in Plugin 'monitor': Undefined index: 0 in file: /var/www/html/cacti-1.0.0/plugins/monitor/monitor.php on line: 935 

Plugin seems to be working just fine.

My current setup is:

Cacti 1.0.0
PHP 5.3.3
Apache 2.2
MariaDB 10.0

**Comment by cigamit** [comment]
Resolving.  Thanks for testing.
