### ISSUE TITLE
How to display title and uptime in the monitor plugin?

### ISSUE THREAD

**Issue by Israellgg** [Cacti/plugin_monitor#181]
I recently installed Cacti version 1.2.27 at my workplace.

In the old version they used here, the monitor plugin displayed the title and uptime. In the version I installed, it only shows the title when the view is in Default. The only available options are showing just the icon or just the time.

I would like it to show both the title and uptime. How can I do this?

Cacti version: 1.2.27
Monitor Plugin version: 2.7
Thold Plugin version: 1.8.1

exemple:
https://github.com/Cacti/plugin_monitor/assets/11051992/62da242d-425a-403f-ae74-f94ee8f0b44b

**Comment by TheWitness** [comment]
![image](https://github.com/user-attachments/assets/cd31fc69-a159-4265-821f-6db7bf555d32)

**Comment by TheWitness** [comment]
**Tiles and Time**
