### ISSUE TITLE
Color coding monitor page list view

### ISSUE THREAD

**Issue by dallenk** [Cacti/plugin_monitor#182]
# Feature Request

## Is your feature request related to a problem? Please describe

not really a problem,  but aesthetically would look nice and easy to identify.   When using the monitor page in list mode, there isn't any color coding on the lines showing status.   It would be nice to show here the state of the devices.
![image](https://github.com/user-attachments/assets/f21c6f42-a89c-47ef-b7df-4b1e1bb06276)

**Comment by cigamit** [comment]
Moving this over to the Monitor plugin repo, instead of the main Cacti repo.

**Comment by TheWitness** [comment]
It was a larger change than I thought it would be, but it's done.

**Comment by TheWitness** [comment]
Example below:

![image](https://github.com/user-attachments/assets/d8af637f-6f24-4954-819a-c8db6645b87d)
