### ISSUE TITLE
Add Ordering and Row Counters to List View

### ISSUE THREAD

**Issue by TheWitness** [Cacti/plugin_monitor#183]
**Is your feature request related to a problem? Please describe.**

Currently the list view seems very primitive with no ability to order the columns or even limit the number of rows.

**Describe the solution you'd like**

Make it more like a normal Cacti page.

**Describe alternatives you've considered**

None other than that.

**Additional context**

Makes that interface much more consumable.

**Comment by dallenk** [comment]
wow, that is a great improvement!

**Comment by TheWitness** [comment]
Yea, I'm trying to get that into more of what I would refer to as professional quality.  It was a bit messy before.

**Comment by TheWitness** [comment]
@sgvfr, if you want to do some QA, that would be nice.

**Comment by dallenk** [comment]
@TheWitness it seems the devices shown isn't saved between sessions.   I usually set to 100 but every time I log in it looks like 10 is selected.  Is that per session or should it save as a preset?
![image](https://github.com/user-attachments/assets/cad98b6f-b6a9-4bb0-90ed-b87b1b746eea)

**Comment by TheWitness** [comment]
It's supposed to save.  Log a fresh bug and I'll get it over the weekend.

**Comment by TheWitness** [comment]
It's working for me.  Tested it over the weekend, but there was a bug in saving new dashboards that was resolved.  There appear also to be some jQueryUI quirks with the new 1.14 version that we have to work through with regard to the console visibility.  Lot's of things on my list right now, chief amoungst them is getting the new plugin interface finalized.
