### ISSUE TITLE
Monitor Plugin Permissions issues

### ISSUE THREAD

**Issue by raptor01uk** [Cacti/plugin_monitor#19]
Created a user with zero permissions, added it to a group with permissions to view some devices but not all, change the view options to tree under the monitor tab and user is able to see only the devices they have permissions for. Change the view option to default and they can see all devices, hover over a device that the user has no permissions for and see all snmp information regarding the device. The user default is to deny on everything and yet they can still see everything using the monitor tab.
Changed for settings for view to default with permissions and same issue occurs.

See the attached for settings:

Permissions set to Deny on all
![permissions](https://cloud.githubusercontent.com/assets/26091343/23412434/67152d20-fdcd-11e6-8377-29bd4b52754c.PNG)

Works fine with tree view selected
![tree veiw](https://cloud.githubusercontent.com/assets/26091343/23412431/66ae3e80-fdcd-11e6-8168-ff38a2380936.PNG)

Can see all devices with Default view selected
![default view](https://cloud.githubusercontent.com/assets/26091343/23412430/66a8acb8-fdcd-11e6-93d1-e305165f7212.PNG)

Can hover and see all device information
![hover](https://cloud.githubusercontent.com/assets/26091343/23412545/c2ead910-fdcd-11e6-9898-ee562c30d3b5.PNG)

**Comment by cigamit** [comment]
Resolved, thanks for reporting!
