### ISSUE TITLE
Monitor host status

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_monitor#2]
All of my hosts are showing "Alert Ping" and red as status on monitor.php, even though the status in hosts database field are all a value of 3. According to the array $icolorsdisplay in monitor.php, those hosts should be showing "Up". I am running the latest dev commits on both cacti and monitor. What am I doing wrong?

**Comment by cigamit** [comment]
there was a defect where if you did not set an alert or warn threshold, it would report them as breached.  should be fixed now.

**Comment by smiles1969** [comment]
Works ☺ TY
