### ISSUE TITLE
No Tab

### ISSUE THREAD

**Issue by peter-thoenen** [Cacti/plugin_monitor#21]
Have enabled user access to monitor tab but tab does not show up.  User can still access the information though directly via a saved URL (https://server/cacti/plugins/monitor/monitor.php)

![image](https://cloud.githubusercontent.com/assets/15895994/25642810/da974e72-2f37-11e7-8dd5-5d6cb819da1d.png)

**Comment by cigamit** [comment]
Any errors in the Cacti log?

**Comment by peter-thoenen** [comment]
Negative.

**Comment by cigamit** [comment]
If you have the user permission, there may be a bug where you have to log off and on again.  Also, please check the other themes for the presence of the tab.  If it's there and not in classic, then we know that there likely may be an issue with the php-gd module not working.  You have php-gd installed right?

**Comment by cigamit** [comment]
Guess what, I confirmed that there is no monitor tab in classic.  To my surprise actually.

**Comment by cigamit** [comment]
Ope, it was just hidden due to the wrapping setting.  My bad.  It's actually there.  I just had to zoom out.  There is an open ellipsis issue, may not be logged, in order to allow you to view all top tabs on smaller screens in all themes (except maybe classic).  It's important for phones and tablets.

**Comment by peter-thoenen** [comment]
To your above comment, doesn't exist (at least for me) in the other themes as well.

First image is to show no tabs (even in dark) and also user perms (yes I have logged on and off).
Second image to show if I go there directly via the URL (i.e. not a perm issue as I can access it).

![capture_1](https://cloud.githubusercontent.com/assets/15895994/25726291/31856b46-30bf-11e7-8a98-7aeeacb251f2.PNG)
![capture_2](https://cloud.githubusercontent.com/assets/15895994/25726290/31839762-30bf-11e7-95c0-423518a60e3b.PNG)

**Comment by peter-thoenen** [comment]
To other comment above, yes @ php-gd (#yum list installed | grep gd ---> php-gd.x86_64 )

Not sure what other tabs I should see at this point TBH lol, plugin list is:

![image](https://cloud.githubusercontent.com/assets/15895994/25726730/4389c74a-30c1-11e7-8a9f-76f8bd6cb420.png)

**Comment by cigamit** [comment]
Oh, your plugins are installed but not enabled.  Click the Green Icons next to each one.

**Comment by cigamit** [comment]
Just as a note, having a plugin disabled still shows the Settings and Permissions of that plugin (so that it can be configured before completely enabling it for users to use).

**Comment by peter-thoenen** [comment]
Will give that a shot when I get in the office tomorrow but you sure about that? I thought the green check box meant "enabled".  I.e. if it's not enabled then why when I directly go the URL (i.e. https://server/cacti/plugins/monitor/monitor.php) does it work?

**Comment by cigamit** [comment]
Yes, that should be correct.  The reason why going to the URL works, is that plugins generally don't check if they are enabled or not.

**Comment by peter-thoenen** [comment]
There a way to troubleshoot why a plugin won't enable? nothing in error log.  Per your comment above I enabled all of them (well except the ones that won't enable no matter how often clicked, see below).  I'm fine limiting this to "monitor" but it's all the non-orange ones.

![image](https://cloud.githubusercontent.com/assets/15895994/25882198/73844914-34dd-11e7-9356-743bcd34c623.png)

**Comment by cigamit** [comment]
Resolved.
