### ISSUE TITLE
Large text for systems with outages / doesn't wrap

### ISSUE THREAD

**Issue by peter-thoenen** [Cacti/plugin_monitor#22]
See attached screen shot.  Systems with "issues" have giant text (maybe intentionally, maybe not) but it should wrap or something.

![image](https://cloud.githubusercontent.com/assets/15895994/25642855/232d4a92-2f38-11e7-902c-4d965fee66b4.png)

**Comment by cigamit** [comment]
If you use the Browsers debug feature, can you hover over the text and then in the debug window, take a screen show of what appears in the CSS section when hovering over that text.  Upload the screen shot.  It's likely the classic monitor CSS.  If you switch to the Dark them, let me know if it goes away.

**Comment by peter-thoenen** [comment]
You are correct, changed from "Classic" to "Dark" and problem resolves; ditto in modern and paw.

Not sure what you want exactly in the screenshot so I right clicked the link in Chrome->"Inspect item" and snapped it:

![image](https://cloud.githubusercontent.com/assets/15895994/25679879/a079728e-2fea-11e7-8357-0d35aef7d84d.png)

**Comment by cigamit** [comment]
You may find this link useful.  https://www.youtube.com/results?search_query=github+how+to+create+a+pull+request

**Comment by cigamit** [comment]
This is resolved now.
