### ISSUE TITLE
Feature Request: Custom Tiles or at least the old ones as an option

### ISSUE THREAD

**Issue by peter-thoenen** [Cacti/plugin_monitor#23]
Not a fan of the "new" stacked server icons.  Would if you could add the old ones from 0.6.2 as an option as well (even if not default) or even better, add some way (or directions in the readme) to add custom icons.  If going the latter route would be great if could do on a "device" level or (worse case) tree header or device template level.  Would love to be able to quickly and visually differentiate different types of devices.

**Comment by cigamit** [comment]
We are using Glyphs from fontawesome.  If you know of or can find an an OSS friendly library that gives good collection of Glyphs, or icons, we can consider it.  I'm going to have to put that monkey on your back though.

**Comment by peter-thoenen** [comment]
Ah didn't realized you changed this to use a font over custom icons / images.  Let me check on this, I can live with that monkey on my back

**Comment by peter-thoenen** [comment]
GA and close this
