### ISSUE TITLE
More often host avability checking

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#25]
I would like to check avability more often than getting datas for graphs.

I would see that as another option on "devices".
Check avability by 15/30/60/120/180....sec.

Maybe there should be another daemon for checking avability?

**Comment by netniV** [comment]
This would really come into play with thold and base cacti.  I would suggest opening the request there but I am not sure that it would be possible.  Every poller cycle, graphs are obtained so if your poller cycle is 5 minutes, it will only be able to check the host every 5 minutes.

The change you want would require to have multiple intervals and that isn't something that's achievable at the moment.  One to do the SNMP query check, one to grab all the graph data that's required.

**Comment by netniV** [comment]
As host availability is part of the core, I'm going to close this for now.
