### ISSUE TITLE
Monitor Plugin Integratio with Thold Alarms not functioning.

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_monitor#26]
Upon testing Monitor Plugin Integration with Thold, I have discovered that Monitored Object doesn't change color if THOLD alarm associated with that object are in triggered state:
Monitor Plugin Object:
![dallas](https://cloud.githubusercontent.com/assets/11211789/26640739/8c462a1a-45f6-11e7-891e-4ea78a9b22e0.jpg)
Expected Triggered Color:
![triggered](https://cloud.githubusercontent.com/assets/11211789/26640750/9639612c-45f6-11e7-8bc4-36aa5a252a84.jpg)
Thold Triggered Alarm associated with the object:
![triggered-thold](https://cloud.githubusercontent.com/assets/11211789/26640762/9e840468-45f6-11e7-91ff-ba0e057ed5b6.jpg)

**Comment by cigamit** [comment]
Resolved thanks.
