### ISSUE TITLE
Last Fail problem

### ISSUE THREAD

**Issue by solarbg** [Cacti/plugin_monitor#27]
Hello, i have last version of cacti and plugin_monitor. 
Have problem with last fail. All is 0000-00-00 00:00:00

Os: Ubuntu 16.04
Php version 7.0.15-0ubuntu0.16.04.4
Mysql: 5.7.18
Cacti version Version 1.1.7
plugin_monitor 2.1

**Comment by peter-thoenen** [comment]
Double check this bug fix:

http://forums.cacti.net/viewtopic.php?f=14&t=48424

Supposedly a bug fix was submitted way back in 0.8.9 before github but if you are getting it still, this appears to never have been resolved.  Please confirm if the fix listed in that post fixes it for you

**Comment by solarbg** [comment]
Yes i check this bug fix: 
My function.php is: 
 /* initialize fail and recovery dates correctly */
        if ($hosts[$host_id]['status_fail_date'] == ""){
                $hosts[$host_id]['status_fail_date'] = '0000-00-00 00:00:00';
        }

        if ($hosts[$host_id]['status_rec_date'] == ""){
                $hosts[$host_id]['status_rec_date'] = '0000-00-00 00:00:00';
        }

**Comment by solarbg** [comment]
Well i make some changes in monitor.php and work for me.
add this 
        $dt = '';
        if ($host['status'] < 2 || $host['status'] == 5) {
                $dt = monitor_print_host_time($host['status_fail_date']);
                $downthost = get_timeinstate($host); /* add this line */
}

and change
		if ($host['status'] <= 2 || $host['status'] == 5) {
			$result = "<div " . ($host['status'] == 1 ? 'class="' . $fclass . ' flash monitor_device_frame"':'class="' . $fclass . ' monitor_device_frame"') . " style='width:" . max(80, $maxlen*6) . "px;" . ($float ? 'float:left;':'') . "'><a href='" . $host['anchor'] . "'><i id='" . $host['id'] . "' class='fa $fclass $iclass " . $host['iclass'] . "'></i><br><span class='center'>" . trim($host['description']) . "</span><br><span style='font-size:10px;padding:2px;' class='deviceDown'>$dt</span></a></div>\n";
		} else {

to

		if ($host['status'] <= 2 || $host['status'] == 5) {
			$result = "<div " . ($host['status'] == 1 ? 'class="' . $fclass . ' flash monitor_device_frame"':'class="' . $fclass . ' monitor_device_frame"') . " style='width:" . max(80, $maxlen*6) . "px;" . ($float ? 'float:left;':'') . "'><a href='" . $host['anchor'] . "'><i id='" . $host['id'] . "' class='fa $fclass $iclass " . $host['iclass'] . "'></i><br><span class='center'>" . trim($host['description']) . "</span><br><span style='font-size:10px;padding:2px;' class='deviceDown'>$downthost</span></a></div>\n";
		} else {


My English is not good and i have no experiences with code. This is my first post in github

**Comment by cigamit** [comment]
You guys really need to open a pull request.

**Comment by cigamit** [comment]
Resolved.
