### ISSUE TITLE
add device with CLI and add monitoring!

### ISSUE THREAD

**Issue by dabeani** [Cacti/plugin_monitor#28]
Hi,

Can you add a function, that if a new device will be added with CLI (cacti/cli/add_device.php) to add this devices to the monitoring TAB with some special command.

br
Bernhard

**Comment by cigamit** [comment]
Good point.

**Comment by netniV** [comment]
I think the best solution would be to have an option on the settings -> montior page that shows a default value for monitor when adding a device.  That way both the GUI and CLI can use that option to set the default value of the field.

**Comment by netniV** [comment]
I've added create a patch for this.  New option within the Settings -> Monitor section defines the default to use for new devices.  Works with both CLI and GUI

**Comment by netniV** [comment]
@dabeani did this fix things for you?

**Comment by netniV** [comment]
@cigamit Another one we have had no response to and I added the functionality.

**Comment by dabeani** [comment]
Hi,

Sorry, thank you that you have invested time into that feature.
But now my response to your question. And – don’t be so unhappy if someone (anyone, a guy like me) do not response in-time, but I think this feature is for bigger environments really usable! ☺

Had some troubles with my installation – so I had to do some more work to get things running again.
And – now, it’s working. CLI and Web IF! 
Big thank you for that possibility.

BR
Bernhard

**Comment by netniV** [comment]
No worries, glad it's working.  Just trying to close off issues that don't need to be left open :)  If you had still had an issue we could have reopened. 👍
