### ISSUE TITLE
Bug: When all trees selected: only 1 root container is shown see PICs

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_monitor#31]
In Monitor plugin when all trees selected: only 1 root container is shown "Remote Offices" see PIC.
Other root containers are missing.
![root-tree](https://user-images.githubusercontent.com/11211789/29021196-af8ae49a-7b32-11e7-84d6-cecac95b2ecd.jpeg)

I do have devices associated with other root containers and they are properly shown when individual root container is selected: (In a pic below EDC - Jersey City, NJ root container selected)
![root-tree-jc](https://user-images.githubusercontent.com/11211789/29021294-05172b4e-7b33-11e7-9457-b5a924a4dde6.jpeg)

Available "root containers":
![contaners](https://user-images.githubusercontent.com/11211789/29021479-9e350b16-7b33-11e7-8c42-68f34858872e.jpeg)

Please let me know if additional clarifications are needed.

**Comment by cigamit** [comment]
Yea, I noticed that as well.  Likely a simple fix, just need to create some time to fix it.

**Comment by cigamit** [comment]
Resolved.

**Comment by ikorzha** [comment]
Thank you so much for the fix! Tested works great now!
