### ISSUE TITLE
Ennormous big font when host is down

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#32]
Skin: Modern
View: Default
Browser: FF, Chrome, Opera

![wymazane_dane_prywatne](https://user-images.githubusercontent.com/17087236/29712601-f955fba2-899a-11e7-96f7-673a87ea815a.png)

**Comment by cigamit** [comment]
I could have sworn this was fixed.  Is this Tree View?

**Comment by cigamit** [comment]
Wait... Default view.  What is your browser as that does not look a like the Modern Skin.

**Comment by cigamit** [comment]
I suspect that your monitor is out of data.  Please update to the latest and don't hack.

**Comment by interduo** [comment]
Sorry. This is modern skin with border set to black.

**Comment by interduo** [comment]
Ok - I was using master. This is resolved in develop branch.
