### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_monitor#36]
Hi There,

Just a couple of missing bits

![chrome_2017-09-05_15-22-46](https://user-images.githubusercontent.com/13456559/30044320-852459c2-9250-11e7-81aa-b92a2599fd05.png)
![chrome_2017-09-05_15-23-42](https://user-images.githubusercontent.com/13456559/30044319-85243d70-9250-11e7-8014-ed81b51e3a36.png)
![chrome_2017-09-05_15-21-20](https://user-images.githubusercontent.com/13456559/30044321-852494c8-9250-11e7-803b-19ff01b70878.png)

**Comment by cigamit** [comment]
Back at it tonight.  Going to take a look shortly.

**Comment by cigamit** [comment]
So, you missed a few and so did I.  Should have them all now.
