### ISSUE TITLE
Layout with Long Device Names

### ISSUE THREAD

**Issue by stueh** [Cacti/plugin_monitor#37]
Hi All,

I have an interesting issue which popped up - not major, but more of an annoyance. Some of our devices have longer device names. I've found that this doesn't format very well in the monitor.php webpage (see picture below). I'm not much with PHP/HTML, so wondering if anyone would know a way to tweak the formatting so that it's all nice without the last item dropping to the next row by itself, or the blank column on the right?

![image](https://user-images.githubusercontent.com/29741692/30841568-4e04c4f0-a2bc-11e7-953e-63661f14e8ef.png)

Cheers!

**Comment by interduo** [comment]
I can confirm that bug.

**Comment by cigamit** [comment]
Is this just the modern theme.  Can soneone please confirm?

**Comment by interduo** [comment]
After upgrading to newest version this doesn't exists.
