### ISSUE TITLE
List instead of icons

### ISSUE THREAD

**Issue by lbsou** [Cacti/plugin_monitor#39]
Hi!

Would it be possible to have a list instead of the icons with the same data as the "onmouseover" data?

Thanks!

**Comment by cigamit** [comment]
Seems like an interesting idea.  When I get free time.  Not going to be soon unfortunately.

**Comment by netniV** [comment]
I was literally just looking at this plugin thinking the same thing.  It also needs to obey the sorting rules too if in tree mode.

**Comment by netniV** [comment]
This has now been introduced with basic effect in PR #50

**Comment by netniV** [comment]
@lbsou Can you close this if everything is OK with you?

**Comment by lbsou** [comment]
Thank you, nice job!
