### ISSUE TITLE
Validation error in Cacti Version: 0.8.8h

### ISSUE THREAD

**Issue by bouroo** [Cacti/plugin_monitor#4]
I clone plugin_monitor into cacti 0.8.8h plugins path, then in Console -> Plugin Management -> install old plugin message "Validation error." appear. What should I do?

**Comment by bouroo** [comment]
Update now I change "plugin_monitor" to "monitor" can install but I cannot use cacti anymore Y-Y.

/var/log/nginx/error.log
> PHP message: PHP Fatal error:  Call to undefined function reports_get_format_files() in /srv/cacti/plugins/monitor/setup.php on line 269" while reading response header from upstream, client: 192.168.67.130, server: _, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php5.6-fpm.sock:"

**Comment by cigamit** [comment]
This plugin only works with Cacti 1.0

**Comment by bouroo** [comment]
OK, Thx. @cigamit
I will update to cacti 1.0

**Comment by cigamit** [comment]
FYI, Cacti 1.0 is still under heavy development, so I wouldn't upgrade your production environment to it.

**Comment by anumomin** [comment]
I cannot get any of plugins working with 0.8.8h. 
I can see folders in plugins folders but there is no tab... Users have rights to access all plugins..
