### ISSUE TITLE
PHP Error 

### ISSUE THREAD

**Issue by leonw11** [Cacti/plugin_monitor#45]
I get this error messages in Cacti logging.

I have tried to fix it with errorcode 18, without any succes.

**Cacti Log:**

11/12/2017  23:55:05 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/monitor/monitor.php: 103  draw_page)(/plugins/monitor/monitor.php: 129  render_default)(/plugins/monitor/monitor.php: 641  render_host)(/plugins/monitor/monitor.php: 956  CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
--
11/12/2017 23:55:05 - ERROR PHP NOTICE in  Plugin 'monitor':  Undefined offset: 127 in file:  /usr/share/cacti/plugins/monitor/monitor.php  on line: 956
11/12/2017 23:55:05 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/monitor/monitor.php: 103  draw_page)(/plugins/monitor/monitor.php: 129  render_default)(/plugins/monitor/monitor.php: 641  render_host)(/plugins/monitor/monitor.php: 956  CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
11/12/2017 23:55:05 - ERROR PHP NOTICE in  Plugin 'monitor':  Undefined offset: 46 in file:  /usr/share/cacti/plugins/monitor/monitor.php  on line: 956
11/12/2017 23:55:05 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/monitor/monitor.php: 103  draw_page)(/plugins/monitor/monitor.php: 129  render_default)(/plugins/monitor/monitor.php: 641  render_host)(/plugins/monitor/monitor.php: 956  CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
11/12/2017 23:55:05 - ERROR PHP NOTICE in  Plugin 'monitor':  Undefined offset: 127 in file:  /usr/share/cacti/plugins/monitor/monitor.php  on line: 956
11/12/2017 23:55:05 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/monitor/monitor.php: 103  draw_page)(/plugins/monitor/monitor.php: 129  render_default)(/plugins/monitor/monitor.php: 641  render_host)(/plugins/monitor/monitor.php: 956  CactiErrorHandler)(/lib/functions.php: 4408 cacti_debug_backtrace)
11/12/2017 23:55:05 - ERROR PHP NOTICE in  Plugin 'monitor':  Undefined offset: 127 in file:  /usr/share/cacti/plugins/monitor/monitor.php  on line: 956

Plugin seems to be working just fine.

My current setup:
Centos 6.9 / Apache/2.2.15 /  PHP 5.6.32 (cli) (built: Oct 25 2017 07:00:59)
Cacti Version 1.1.28 /  mysql  Ver 14.14 Distrib 5.7.20,

**Comment by netniV** [comment]
This would suggest that you have a host with a status that Monitor does not recognise.  Montior knows these classes:
```
$iclasses = array(
        0 => 'deviceUnknown',
        1 => 'deviceDown',
        2 => 'deviceRecovering',
        3 => 'deviceUp',
        4 => 'deviceThreshold',
        5 => 'deviceDownMuted',
        6 => 'deviceUnmonitored',
        7 => 'deviceWarning',
        8 => 'deviceAlert',
);
```

If your status is outside of this, it falls over which in itself is probably a bug as it should default to Unknown

**Comment by netniV** [comment]
I've submitted a patch for this.  Basically, something set your host to be statuses of 46 and 127.  This is likely to be another plugin since I couldn't find anything in the base system that sets those values for status.

What plugins do you have installed?

**Comment by netniV** [comment]
@leonw11 is this still an issue for you?

**Comment by netniV** [comment]
@cigamit We have had no response on this and I did correct the issue, so I think we should close this.
