### ISSUE TITLE
After latest pull request 50 Plugin monitor gets disabled with Call to undefined function 

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_monitor#51]
2018/02/24 16:33:08 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'monitor'
--
2018/02/24 16:33:08 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4446 cacti_debug_backtrace)
2018/02/24 16:33:08 - ERROR PHP ERROR in   Plugin 'monitor': Call to undefined function get_md5_include_css() in  file: /var/www/html/plugins/monitor/monitor.php on line: 136

**Comment by netniV** [comment]
Right, that will be a version requirement. I thought I'd put that into the INFO file, and I've just double checked that I did. This leads to a new bug ... upgrading a plugin isn't checking the version requirements. You need to have Cacti v1.1.35 to use the updated monitor as it relies on functionality from that.

You will either need to roll back Monitor or upgrade Cacti.

**Comment by netniV** [comment]
As I have now opened the issue on the cacti base that reflects this problem, you should close this issue now.  You're resolutions are still one of the two above.

**Comment by ikorzha** [comment]
Thank you for the info. I now understand the requirement.
