### ISSUE TITLE
Place the Monitor filter inside of a filterTable to make it responsive

### ISSUE THREAD

**Issue by cigamit** [Cacti/plugin_monitor#53]
This will allow better rendering on mobile devices.

**Comment by netniV** [comment]
It gave me headache's just trying to get the layout to be consistent as it was... ;-)

Using just the original filterTable, the layout was making all the fields a different length, so it looked a mess.  So I came up with many different layouts to try and accomplish a nice look before settling on the below to try and sort that as everything else just looked wrong.

```
+---------------------------------------------------------------------=
| +-----------+-----------+-----------+-----------+  |  +----------+  |
| | filter    | view      | grouping | refresh    |  |  | buttons  |  |
| +-----------+-----------+-----------+-----------+  |  +----------+  |
| |  crit     | size      | grpfilter |           |  |  | text     |  |
| +-----------+-----------+-----------+-----------+  |  +----------+  |
+---------------------------------------------------------------------=
```

As you can see, It's basically, a two column table, with a left table for the drop downs, and a right table for the buttons/text.  This solved the main headaches being that
- buttons / text were not justifying with each other
- the widths still didn't look quite right so I added an important width for the monitor select/buttons.
- the grpfilter is optional depending on grouping so the cell was disappearing if not in use.  (The the code was changing that between a hidden `input` and a `select`).

I guess it could be simplified now that I got it to the final layout of above and using a drop down function.

**Comment by cigamit** [comment]
Yea, I get it.  You know the embarrassing thing is that the grid layout is easy once you adopt CSS3.  Once you goto a CSS3 browser (all modern except IE11), you can use flexi-grid layout which makes the rendering below the filter a cake walk.

I would not rush it though, we have other things more important at the moment.

**Comment by cigamit** [comment]
This is resolved now.
