### ISSUE TITLE
Monitor plugin  render host and tree errors in list view

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_monitor#55]
netniV introduced a patch for the issue below, I have tested it and it resolved the errors below.
Can you please be kind enough to patch the github version with below, I do not want to loose track of this fix.

Apply this patch and see if it disappears:

diff --git a/monitor.php b/monitor.php
index d8962c0..452b1b5 100644
--- a/monitor.php
+++ b/monitor.php
@@ -1354,6 +1354,7 @@ function render_footer_list($hosts) {
 }

 function render_host_list($host) {
+       global $criticalities;
        if (!is_device_allowed($host['id'])) {
                return ;
        }

2018/02/25 22:33:46 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/monitor/monitor.php: 122 draw_page)(/plugins/monitor/monitor.php: 145 render_tree)(/plugins/monitor/monitor.php: 961 render_host)(/plugins/monitor/monitor.php: 1082 render_host_list)(/plugins/monitor/monitor.php: 1379 CactiErrorHandler)(/lib/functions.php: 4624 cacti_debug_backtrace)

2018/02/25 22:33:46 - ERROR PHP NOTICE in Plugin 'monitor': Undefined variable: criticalities in file: /var/www/html/plugins/monitor/monitor.php on line: 1379
2018/02/25 22:33:46 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/monitor/monitor.php: 122 draw_page)(/plugins/monitor/monitor.php: 145 render_tree)(/plugins/monitor/monitor.php: 961 render_host)(/plugins/monitor/monitor.php: 1082 render_host_list)(/plugins/monitor/monitor.php: 1379 CactiErrorHandler)(/lib/functions.php: 4624 cacti_debug_backtrace)

**Comment by cigamit** [comment]
Done.  I just opened a new issue that I found in my environment. #57

**Comment by netniV** [comment]
@ikorzha Have you tried the update? Does this now rectify this issue? If so, please close.

**Comment by ikorzha** [comment]
tested, working thank you very much for a quick response!
