### ISSUE TITLE
Mute button unmutes automatically after pressed

### ISSUE THREAD

**Issue by cigamit** [Cacti/plugin_monitor#57]
Even if hosts are in alert, the mute button should stay muted until a new alert comes in or a new host goes down.  Right now that function, that was working perfectly is broken.

**Comment by netniV** [comment]
I'll take a look at why that would be broken.  I don't recall touching anything related to the alert part.  When you say it unmutes, is that straight away? I'm presuming no errors in the logs as you didn't provide any.

**Comment by netniV** [comment]
Also, does that occur after the #56 fix?

**Comment by netniV** [comment]
@cigamit does this update still have the same issue?

**Comment by cigamit** [comment]
Still broken.

![mutebroken](https://user-images.githubusercontent.com/957322/36935723-bd29307a-1ec0-11e8-886d-00158790c50a.gif)

**Comment by netniV** [comment]
OK, I'll take a look.  Thanks for the animation.

**Comment by netniV** [comment]
I can't replicate this on my version.

**Comment by netniV** [comment]
I wonder if this is a theme issue... what theme are you on?

**Comment by netniV** [comment]
I have now managed to reproduce this by adding a sound to my user profile! There is a bug that exists were if there is no sound selected, it defaults to 0 as a filename too.

**Comment by netniV** [comment]
OK, so here's your fix 👍

**Comment by cigamit** [comment]
Thanks!
