### ISSUE TITLE
Cacti Version 1.1.36 - Monitor Latest Develop Branch

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/plugin_monitor#59]
If i use "view as list" and click on column "Status" i have this error into cacti log:

2018/03/06  14:58:45 - CMDPHP Input Validation Not Performed for 'sort_direction'  Backtrace: (/plugins/monitor/monitor.php: 102  validate_request_vars)(/plugins/monitor/monitor.php: 604  validate_store_request_vars)(/lib/html_utility.php: 679  update_order_string)(/lib/html_utility.php: 722  get_request_var)(/lib/html_utility.php: 328  html_log_input_error)(/lib/html_validate.php: 44 cacti_debug_backtrace)
2018/03/06 14:58:45 - CMDPHP Input Validation Not Performed for  'sort_column' Backtrace: (/plugins/monitor/monitor.php: 102  validate_request_vars)(/plugins/monitor/monitor.php: 604  validate_store_request_vars)(/lib/html_utility.php: 679  update_order_string)(/lib/html_utility.php: 698  get_request_var)(/lib/html_utility.php: 328  html_log_input_error)(/lib/html_validate.php: 44 cacti_debug_backtrace)
2018/03/06 14:58:31 - CMDPHP Input Validation Not Performed for  'sort_direction' Backtrace: (/plugins/monitor/monitor.php: 102  validate_request_vars)(/plugins/monitor/monitor.php: 604  validate_store_request_vars)(/lib/html_utility.php: 679  update_order_string)(/lib/html_utility.php: 722  get_request_var)(/lib/html_utility.php: 328  html_log_input_error)(/lib/html_validate.php: 44 cacti_debug_backtrace)
2018/03/06 14:58:31 - CMDPHP Input Validation Not Performed for  'sort_column' Backtrace: (/plugins/monitor/monitor.php: 102  validate_request_vars)(/plugins/monitor/monitor.php: 604  validate_store_request_vars)(/lib/html_utility.php: 679  update_order_string)(/lib/html_utility.php: 698  get_request_var)(/lib/html_utility.php: 328  html_log_input_error)(/lib/html_validate.php: 44 cacti_debug_backtrace)

**Comment by netniV** [comment]
That's an error in using the wrong table header.  There should be no sort options currently because the sorting is handled at a far higher level.  It may be something that gets implemented in the future but right now it shouldn't really be there.

**Comment by netniV** [comment]
I've applied a patch to my repo for this.

**Comment by netniV** [comment]
This should be in the last develop branch now.  Close once confirmed.

**Comment by anarkia1976** [comment]
Fixed, thanks a lot as always.
