### ISSUE TITLE
Double scroll bars in Cacti 1.1.36

### ISSUE THREAD

**Issue by chathurag** [Cacti/plugin_monitor#60]
Not compatible resolution with cacti 1.1.36

**Comment by netniV** [comment]
Can you post a screenshot of the issue?  I'm using it with 1.1.36 without a problem.

**Comment by chathurag** [comment]
![cacti](https://user-images.githubusercontent.com/35136010/37148289-e73bf6ee-22ef-11e8-821e-8a763e23c8cf.png)

**Comment by anarkia1976** [comment]
I don't have this problem with modern theme and firefox.

**Comment by netniV** [comment]
There is an issue with the classic theme, but it appears to be caused more by the base classic theme.  However, I am fixing it up so that Monitor works 👍 

I'm just going to go test all the other themes to be sure there are no issues there either.

**Comment by netniV** [comment]
So this is now in my repo, with a pull request on the way.

**Comment by chathurag** [comment]
not yet resolved in latest update for google chrome..

**Comment by netniV** [comment]
It's in my repo I haven't created a pull request for it.

**Comment by netniV** [comment]
This should now be merged in the develop branch.  Please test and close this issue.

**Comment by chathurag** [comment]
Now OK
