### ISSUE TITLE
Monitor Reboot Notification

### ISSUE THREAD

**Issue by chathurag** [Cacti/plugin_monitor#61]
Monitor device reboot notification sent to email lists other than defined.

**Comment by netniV** [comment]
Please give more details.

**Comment by chathurag** [comment]
There are two different Notification lists created. One is for Threshold and other one is for reboot notification. However Device reboot notification also sent to the Thold notification list even only selected notification list for monitor.

**Comment by netniV** [comment]
Monitor uses the same notification lists that THold does for alerts. Which lists it uses depends on the thold notification type, Disabled, Global List, Notification List, Both Global and Notification.  

It uses the device settings, not a threshold.

**Comment by netniV** [comment]
```sql
SELECT thold_send_email, thold_host_email
                                FROM host
                                WHERE id = <id>
```

**Comment by chathurag** [comment]
In the following Settings we can select Notification list as different from the THOLD. But according to your answer there is no use then?

![cacti](https://user-images.githubusercontent.com/35136010/37255943-dafc746c-2579-11e8-90a5-9ac13ce4fc18.PNG)

**Comment by netniV** [comment]
That does not override the THold's but will be used in addition to them.  I guess an option should be added to prevent the inclusion of Threshold notifications lists.

**Comment by chathurag** [comment]
Is it possible to above Notification list to override THOLD notification list.

**Comment by netniV** [comment]
Not currently.  An option could be added to suppress THOLD notifications in favour of Monitor one.  It shouldn't take too much to do.

**Comment by netniV** [comment]
Turns out, that notification list was not being used at all.  I have now updated the code to use that list if set, plus provide an option to include the thresholds or not.  This is covered by PR #65

**Comment by netniV** [comment]
This has now been merged in the develop branch
