### ISSUE TITLE
CSS Layout Overlaps

### ISSUE THREAD

**Issue by rtripon** [Cacti/plugin_monitor#64]
Hello,
After last pull, I've notice there's something wrong with the layout. It overlaps if selected on TREE

**Comment by netniV** [comment]
Can you provide a screenshot ?

**Comment by rtripon** [comment]
I thought I did..
![monitor tree layout](https://user-images.githubusercontent.com/28921178/37475375-405615b2-287b-11e8-8463-d17453da83c6.jpg)

**Comment by netniV** [comment]
This should be fixed in PR #65

**Comment by rtripon** [comment]
Yep, I've pull'ed from your rep. Thank you.
