### ISSUE TITLE
Monitor Sorting issue

### ISSUE THREAD

**Issue by darkhsu** [Cacti/plugin_monitor#67]
Q:
I have a sorting issue on plugin: monitor.
I set the sorting Type to Manual Ordering, and make sure the Tree is also set to Manual.
But the Monitor tab shows that they're not following what I set.

A:
the monitor plugin is putting the parent AFTER the children

Link : 
https://forums.cacti.net/viewtopic.php?f=14&t=58758&p=273080#p273080

**Comment by hellspawndf** [comment]
I have the same problem. Monitor always sort by ID. The Graph Tree is ok, though.

**Comment by netniV** [comment]
I thought this had been addressed recently.

**Comment by darkhsu** [comment]
So.....Is there a fix?

**Comment by netniV** [comment]
The systems that I have are all automatically sorted, can you provide me any screenshots of the tree and of the monitor screen, plus the various options you are using ?  I can then try and work backwards to work out where it's doing this in the wrong order.

**Comment by darkhsu** [comment]
Please follow to this link
https://forums.cacti.net/viewtopic.php?f=14&t=58758&p=273080#p273080

Thanks
P.S: If more info is needed, please let me know, this problem cause me very hard to find my device on monitor tab.

**Comment by netniV** [comment]
Thanks for the back link. Saves me going to look for it when I get to this.

**Comment by netniV** [comment]
I've been reviewing this one and it's a bigger change than I thought as the code is just assuming that position is the key.  That could mean two items have the same position but on different branch parents and so things may be out of sequence.  Bit of a rework involved to ensure that the tree hierarchy is obeyed.  Additionally, whilst the tree is being checked for having permission, the branches are not yet there is a function in `lib/auth.php` called `get_allowed_branches()` that suggests we should be checking for it.

**Comment by amaybz** [comment]
I also have the same issue, it seems to be sorting all my Trees by there ID instead of what i select in the Tree Options.

**Comment by cigamit** [comment]
This is resolved now.
