### ISSUE TITLE
Tree Group View overlapping

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#7]
Monitor plugin host view = Tree. Medium Size

When group does have more host than one line can carry. 
The second group is overlapping it.

![cacti](https://cloud.githubusercontent.com/assets/17087236/20428597/49269170-ad8a-11e6-84c0-8dc76b01fa1e.png)

**Comment by interduo** [comment]
Height of the group has static declaration instead of float.

**Comment by cigamit** [comment]
Please resolve this through a pull request.  See my other comments on this pull request topic.
