### ISSUE TITLE
Feature request: Child-Parent relationships

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_monitor#70]
Hi there,

In the past wasn't very keen on using monitor to alert for real and lately I've started to set a bunch of devices up to do so and found out a bit annoying the lack of parent-child relationships.

Would be nice to have, to start with, the ability to declare at least one device as parent of many. That way if Daddy is down, will alert with a message like Daddy is down so kids aren't available at this moment.

Sounds reasonable?

**Comment by netniV** [comment]
It requires a change to the core really, something that's been discussed before.  If the core had a heirachical relationship between devices, it could quite easily be transposed to plugins.

**Comment by jpobeda** [comment]
Uhm I see, well I had to try..There is nothing else pushing for this to be implemented right? So we shouldn't hold our breathe for it right?

**Comment by netniV** [comment]
I wanted it too.  Maybe when 1.3 comes around we will have worked out a way.  It's one of those things a bit like notifications were it could cause breaking changes to existing stuff if we are not careful, plus we have to make sure there is no circular referencing going on.

**Comment by netniV** [comment]
I'm going to close this as we still have the issue open in the Core repository: https://github.com/Cacti/cacti/issues/1330
