### ISSUE TITLE
Only one tile being displayed per row being displayed

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_monitor#71]
On monitor tab using tiles or tree I cannot find a way to adjust the # of tiles per row. In tile view all devices are a single row down the middle of the page.

**Comment by netniV** [comment]
What version are you using and can you provide a screenshot?

**Comment by jdcoats** [comment]
cacti 1.1.38 and monitor 2.3.4
![screen shot 08-22-18 at 01 07 pm](https://user-images.githubusercontent.com/42470924/44479296-b5e29800-a62f-11e8-81b0-9bc89ba3942e.PNG)

**Comment by netniV** [comment]
OK, so I've pushed an update that should resolve this.

**Comment by jdcoats** [comment]
Thanks! It is formatted correctly now. Also with IE I cannot change options on the page. Specifically you change the drop menu but the save button does not work. It works fine with Chrome and Edge. Should I open s separate issue for that as a reminder?

**Comment by netniV** [comment]
Yes.  But my answer should be don't use IE 👍 heh
