### ISSUE TITLE
change the icon

### ISSUE THREAD

**Issue by armanzhakypbayev** [Cacti/plugin_monitor#73]
Hello everybody, i can't change device icons on "Monitor" section, there are bulk of green icons like "server" or something like that, and it's confusing. How can I change it?

**Comment by netniV** [comment]
Currently, there is only one icon.  However, you can change the view to include descriptions

**Comment by armanzhakypbayev** [comment]
Thanks, actually, I am new user of cacti. So can you explain this description

**Comment by netniV** [comment]
Change the combo boxes at the top and the layout will change.  I'm not sure of what combination it is, but somewhere between the style, layout and size combos the description appears.
