### ISSUE TITLE
monitor, triggered and breach thresholds

### ISSUE THREAD

**Issue by SergejLT** [Cacti/plugin_monitor#74]
latest monitor and thold git

selecting in monitor window to monitor "Not Up or Triggered" I asume it would monitor only Triggered tresholds? but it monitors also breached tresholds wich in my situation some has breach duration of 5-10 pollings.

Is it posible to monitor only **triggered th**? and breached th wont appear in main monitor window?

![monitor](https://user-images.githubusercontent.com/32635039/47144058-41df0c00-d2cf-11e8-9b9d-d92d97ecf24e.PNG)

**Comment by netniV** [comment]
Does threshold show those different? I can't recall.

**Comment by SergejLT** [comment]
yes and no.

In Thold
Triggered shows only triggered threshold

![thold_t](https://user-images.githubusercontent.com/32635039/47197947-2bd65780-d372-11e8-9071-0d7e1bf83059.PNG)

Breached shows triggered and breached thresholds

![thold_b](https://user-images.githubusercontent.com/32635039/47197949-2ed14800-d372-11e8-8d70-95f969dfcd51.PNG)

In monitor window there are three selections, when selecting "Not Up or Triggered" it monitors breached and triggered thold. Wich i asume need to monitor only triggered thold?

![monitor_s](https://user-images.githubusercontent.com/32635039/47198056-c20a7d80-d372-11e8-995a-0d7985e79da8.PNG)

**Comment by netniV** [comment]
OK, I will take a look next week at this.  See what I can do.

**Comment by cigamit** [comment]
Resolved.
