### ISSUE TITLE
monitor sound

### ISSUE THREAD

**Issue by SergejLT** [Cacti/plugin_monitor#75]
There is a sound option for downed devices.

![monitor_sound](https://user-images.githubusercontent.com/32635039/47417202-24eb8280-d780-11e8-9fa1-ff4e186e95b1.PNG)

How about sound for Triggered tholds? Is there any possibility to make it work?
For example if any thold or down device or both appears then monitor makes same sound.

**Comment by netniV** [comment]
That would be constantly going off in my environment.  Noisy enough when it's just a site going down.  But I can see the merits of some people wanting that.  Maybe a combo box that lists

* None
* Down
* Breached
* Triggered

In simple terms, that is going from `never sounding` through to `we are going to have a rave with this beat`

**Comment by SergejLT** [comment]
that looks promising with the slection box :)

**Comment by cigamit** [comment]
This is resolved.
