### ISSUE TITLE
Monitor attempts to get status for non-server elements

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#76]
2018/10/31 08:25:50 - CMDPHP Validation Error, Variable:id, Value:crit-button Backtrace: (/plugins/monitor/monitor.php[100]:validate_request_vars(), /plugins/monitor/monitor.php[632]:validate_store_request_vars(), /lib/html_utility.php[669]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())

**Comment by netniV** [comment]
I will take a look shortly.

**Comment by netniV** [comment]
Did you do anything when this error appeared?  If the value isn't present, it defaults to -1, if it is present it should be an integer.

**Comment by interduo** [comment]
Don't know that. This error showed in "Logs" panel many times. 
I just found that error and thought that I need to make an issue. 
I didn't view the monitor code because lack of time.

**Comment by netniV** [comment]
Can you see if you have an access logs showing that id= in the GET request?  If it's a post, I am wondering what's causing it.  Also what version are you running?

**Comment by interduo** [comment]
I've updated to branch: develop from beta2. 

Log:
`2018/10/31 17:46:38 - CMDPHP Validation Error, Variable:id, Value:size-button Backtrace: (/plugins/monitor/monitor.php[100]:validate_request_vars(), /plugins/monitor/monitor.php[632]:validate_store_request_vars(), /lib/html_utility.php[669]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())`

Requests:
```
MYIPADDRESS:) - - [31/Oct/2018:17:46:38 +0100] "GET /plugins/monitor/monitor.php?header=false&action=ajax_mute_all&refresh=30&grouping=default&tree=-1&template=-1&view=default&crit=0&size=monitor_medium&mute=true&status=-1 HTTP/1.1" 200 11816 "https://cacti/plugins/monitor/monitor.php?action=&refresh=30&grouping=default&tree=-1&template=-1&view=default&crit=0&size=monitor_medium&mute=false&status=-1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/70.0.3538.67 Chrome/70.0.3538.67 Safari/537.36"
MYIPADDRESS:) - - [31/Oct/2018:17:46:38 +0100] "GET /plugins/monitor/monitor.php?action=ajax_status&id=size-button HTTP/1.1" 200 2059 "https://cacti/plugins/monitor/monitor.php?action=ajax_mute_all&refresh=30&grouping=default&tree=-1&template=-1&view=default&crit=0&size=monitor_medium&mute=true&status=-1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/70.0.3538.67 Chrome/70.0.3538.67 Safari/537.36"
```

**Comment by netniV** [comment]
Thanks I'll take a look tomorrow.

**Comment by netniV** [comment]
So the problem would seem to be related to hovering over a server's icon.  The reason it's an issue is that the tooltip is actually targeting the entire document's elements rather than just the actual server elements.

This has now been committed to the development code.
