### ISSUE TITLE
Device status information in popup window may contains quotes

### ISSUE THREAD

**Issue by skyjou** [Cacti/plugin_monitor#77]
Should the escape character be removed from popup window?

![image](https://user-images.githubusercontent.com/13309854/48307656-58098080-e58c-11e8-94c2-fa864bdc358f.png)

**Comment by netniV** [comment]
How does it appear on the device page?

**Comment by skyjou** [comment]
Do you mean how to show this window? Just put mouse cursor on the device in monitor page.

The device management page doesn't show escape character:

![image](https://user-images.githubusercontent.com/13309854/48314354-63e45980-e603-11e8-957f-3612d8f4bbfd.png)

**Comment by netniV** [comment]
OK, so appears correctly there just not within the monitor hover part.  I'll take a look sometime this week.

**Comment by netniV** [comment]
Monitor takes that value directly from the snmp_sysDescr field of the host table.  Therefore, if it is displaying those characters, they must already be there.  Can you check the table?

```sql
select id, description, snmp_sysDescr, snmp_sysLocation, snmp_sysContact from host
```

**Comment by skyjou** [comment]
Yes, those characters are in the table. But shouldn't we hide those characters when show information to user?

**Comment by netniV** [comment]
If they are escaped into the DB that way, we will show them that way.  I'm curious why you don't see them on the host.php page that way since I can't see anything handling things differently there either.

My only other thought is that the data for both is being retrieved via JavaScript but then it is passed via JSON on the Monitor page, where it is in the pure output on the host.php page.

I'd have to intercept the calls to see what actual output is being received and how it's being applied.

**Comment by netniV** [comment]
I can't reproduce this, are you still seeing the same issue with the latest version?

**Comment by skyjou** [comment]
Yes. I update monitor plugin to latest version, and I still see the same issue.

**Comment by cigamit** [comment]
@skyjou, Are you using spine or cmd.php for data collection?

**Comment by skyjou** [comment]
I use spine.

![screenshot from 2019-02-18 08-47-39](https://user-images.githubusercontent.com/13309854/52922171-f9f1f380-3359-11e9-8f2a-cdd54401d640.png)

**Comment by cigamit** [comment]
What version of Cacti right now?  I think this problem will solve itself after the next release 1.2.2 of Cacti.

**Comment by skyjou** [comment]
My cacti version is 1.2.1. I will report here if it be solved in the next release.

**Comment by skyjou** [comment]
I just upgrade my Cacti to the latest developing version. I still see the same issue.

**Comment by cigamit** [comment]
Check again.  Let us know.  Also, what is your language default?  The values that are displayed are only updated twice a day.

**Comment by skyjou** [comment]
It is still the same:
![screenshot from 2019-02-19 12-48-59](https://user-images.githubusercontent.com/13309854/52990802-db1c5b80-3444-11e9-857a-1edaf0ed375e.png)

My Cacti language is English:
![screenshot from 2019-02-19 12-46-24](https://user-images.githubusercontent.com/13309854/52990823-f12a1c00-3444-11e9-9743-c1767b7eddf2.png)

**Comment by cigamit** [comment]
What data collector are you using spine or cmd.php?

**Comment by skyjou** [comment]
I use spine.

**Comment by cigamit** [comment]
Is it doing that for all devices, or just some.  I've reviewed spine, and there is no reason except for possibly the device configuration, for this to happen.

**Comment by skyjou** [comment]
There are Cisco switches, Fortinet firewalls, Palo Alto firewalls and Juniper switches in my network. I can find the same issue on all of them in 'Monitor Plugin'.

**Comment by netniV** [comment]
What OS are you running on?
Can you provide the following information:

- OS & Version
- PHP Version
- Cacti Version

**Comment by skyjou** [comment]
* OS & Version: Ubuntu 18.04.2 LTS
* PHP Version: 7.2.15
* Cacti Version: 1.2.2 develop

**Comment by cigamit** [comment]
This is resolved now, but was being caused by local configuration.
