### ISSUE TITLE
Default view is now very small

### ISSUE THREAD

**Issue by KnoAll** [Cacti/plugin_monitor#79]
Just updated to the current release and the display is very small. The dropdown menus are all stacked instead of right to left, and the small/large/etc does not work.
![cacti_monitor](https://user-images.githubusercontent.com/7632685/50354982-190f0900-0502-11e9-97ab-5a2ee6e334d7.png)

**Comment by netniV** [comment]
The current version of monitor should only be working with the 1.2 beta.  Are you running that?

**Comment by KnoAll** [comment]
OK, thanks.
