### ISSUE TITLE
txt based email

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_monitor#80]
Currently Monitor requires html based email client, even if the message is modified to txt only. Can we allow the plugin to send txt based notifications?

**Comment by netniV** [comment]
Monitor uses the core functionality, but I will check later if the right flags are being set to realise that it isn't HTML email.

**Comment by cigamit** [comment]
This should be resolved now.  We leverage the Threshold/Alerting Email option to achieve.

**Comment by jdcoats** [comment]
My email comes as txt with the html printed out.

`body {
margin-left:auto;
margin-right:auto;
}
table {
border-collapse: collapse;
border-spacing: 0;
border: none;
text-align: center;
align-content: center;
width: 100%;
}
.report_table {
background-color:#F9F9F9;
text-align: center;
border: 0;
width: 100%;
margin: auto;
}
.title_row {
background-color: #EAEAEA;
}
.title {
background-color: #EAEAEA;
font-size: 16pt;
text-align: center;
}
.image_table {
}
.image_row {
}
.image_column {
align: center;
}
.image {
}
.text_row {
background-color: #EAEAEA;
}
.text {
background-color: #EAEAEA;
font-size: 16pt;
text-align: center;
}
.left {
text-align: left;
}
.right {
text-align: right;
}
.center {
text-align: center;
}
Monitor Reboot Notification
The following Device's were Rebooted.
See details below for additional information.
DescriptionHostname
EPDMS0210.9.77.101
`

**Comment by cigamit** [comment]
Try again.

**Comment by jdcoats** [comment]
That removes the manual txt "Monitor Reboot Notification The following Device's were Rebooted. See details below for additional information." and still includes the html

`body {
margin-left:auto;
margin-right:auto;
}

table {
border-collapse: collapse;
border-spacing: 0;
border: none;
text-align: center;
align-content: center;
width: 100%;
}

.report_table {
background-color:#F9F9F9;
text-align: center;
border: 0;
width: 100%;
margin: auto;
}

.title_row {
background-color: #EAEAEA;
}

.title {
background-color: #EAEAEA;
font-size: 16pt;
text-align: center;
}

.image_table {
}

.image_row {
}

.image_column {
align: center;
}

.image {
}

.text_row {
background-color: #EAEAEA;
}

.text {
background-color: #EAEAEA;
font-size: 16pt;
text-align: center;
}

.left {
text-align: left;
}

.right {
text-align: right;
}

.center {
text-align: center;
}





DescriptionHostname

C-PhysTrng-SW24-01.TMH.ORG10.9.0.230

`

**Comment by cigamit** [comment]
That is quite odd.  Try again.  You have to update lib/functions.php too.

**Comment by jdcoats** [comment]
still the same

**Comment by cigamit** [comment]
Should be better now.

**Comment by jdcoats** [comment]
thanks! works as expected now
