### ISSUE TITLE
After updating cacti to 1.2.1 Devices wont display in monitor.php anymore

### ISSUE THREAD

**Issue by APPxJason** [Cacti/plugin_monitor#82]
We see the device count when we switch to "tree" view but the devices are not displayed.

**Comment by netniV** [comment]
I will take a look at the weekend but this should be working.

**Comment by netniV** [comment]
I did a test of this and my system was working fine.  See if you have any errors in your log files (apache, php, cacti).

**Comment by APPxJason** [comment]
We gave up and did a clean install, manually added our devices and all is fine.

Thank you.
