### ISSUE TITLE
Hosts deleted, not removed from monitor DB part

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_monitor#83]
I delete some host in cacti 1.2.1, but ti's look like they are still present inside the `plugin_monitor_uptime` table and give an error when you go to the monitor tab, and then come back to another one.

2019/02/15 12:57:07 - ERROR PHP NOTICE in  Plugin 'monitor': Undefined index: id in file: /usr/share/cacti/plugins/monitor/monitor.php  on line: 1169
2019/02/15 12:57:07 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/monitor/monitor.php[106]:ajax_status(), /plugins/monitor/monitor.php[1169]:CactiErrorHandler())
2019/02/15 12:57:07 - ERROR PHP NOTICE in  Plugin 'monitor': Undefined index: status in file: /usr/share/cacti/plugins/monitor/monitor.php  on line: 1171
2019/02/15 12:57:07 - CMDPHP PHP ERROR NOTICE Backtrace:  (/plugins/monitor/monitor.php[106]:ajax_status(), /plugins/monitor/monitor.php[1171]:CactiErrorHandler())
2019/02/15 12:57:07 - ERROR PHP NOTICE in  Plugin 'monitor': Undefined index: availability_method in file: /usr/share/cacti/plugins/monitor/monitor.php  on line: 1180

**Comment by netniV** [comment]
I'm made a tweak, see what that does for you.

**Comment by netniV** [comment]
I've now added code to remove stale entries.

**Comment by arno-st** [comment]
You can try that, it's for both monitor table that hold host id
```php
        if (sizeof($removed_hosts)) {
                db_execute('DELETE FROM plugin_monitor_uptime
                        WHERE host_id IN (SELECT * FROM (SELECT mu.host_id
                        FROM plugin_monitor_uptime AS mu
                        LEFT JOIN host AS h
                        ON h.id=mu.host_id
                        WHERE mu.host_id IS NOT NULL AND h.id IS NULL) AS temptable)');

                db_execute('DELETE FROM plugin_monitor_reboot_history
                        WHERE host_id IN (SELECT * FROM (SELECT mu.host_id
                        FROM plugin_monitor_reboot_history AS mu
                        LEFT JOIN host AS h
                        ON h.id=mu.host_id
                        WHERE mu.host_id IS NOT NULL AND h.id IS NULL) AS temptable)');
        }
```

Sorry not to present as diff, but it's line 181 poller_monitor.php
