### ISSUE TITLE
Unknown column 'mu.id' in 'field list'

### ISSUE THREAD

**Issue by skyjou** [Cacti/plugin_monitor#84]
After upgrade to the latest development version, I see a lot of error messages:

`2019/02/18 00:53:06 - CMDPHP SQL Backtrace: (/plugins/monitor/poller_monitor.php[92]:monitor_uptime_checker(), /plugins/monitor/poller_monitor.php[183]:db_execute(), /lib/database.php[188]:db_execute_prepared())
2019/02/18 00:53:06 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'mu.id' in 'field list'
2019/02/18 00:53:06 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/monitor/poller_monitor.php[92]:monitor_uptime_checker(), /plugins/monitor/poller_monitor.php[182]:sizeof(), CactiErrorHandler())
2019/02/18 00:53:06 - ERROR PHP WARNING in Plugin 'monitor': sizeof(): Parameter must be an array or an object that implements Countable in file: /plugins/monitor/poller_monitor.php on line: 182
2019/02/18 00:53:06 - CMDPHP SQL Backtrace: (/plugins/monitor/poller_monitor.php[92]:monitor_uptime_checker(), /plugins/monitor/poller_monitor.php[176]:db_fetch_assoc(), /lib/database.php[449]:db_fetch_assoc_prepared(), /lib/database.php[463]:db_execute_prepared())`

**Comment by cigamit** [comment]
Resolved
