### ISSUE TITLE
Error occur when select list view

### ISSUE THREAD

**Issue by skyjou** [Cacti/plugin_monitor#85]
I get error messages when I select list view:
`
2019/02/18 22:37:25 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/monitor/monitor.php[127]:draw_page(), /plugins/monitor/monitor.php[154]:render_default(), /plugins/monitor/monitor.php[793]:render_host(), /plugins/monitor/monitor.php[1254]:render_host_list(), /plugins/monitor/monitor.php[1590]:CactiErrorHandler())
2019/02/18 22:37:25 - ERROR PHP NOTICE in Plugin 'monitor': Undefined variable: host_avg in file: /opt/cacti-web/plugins/monitor/monitor.php on line: 1590
`

**Comment by skyjou** [comment]
I have a special host with no downed device detection. If I disable monitor on this host, no error message will generate when I click on list view. This seems my config error.

**Comment by cigamit** [comment]
Should be resolved.

**Comment by skyjou** [comment]
Yes. I re-enable the host without downed device detection, and there is no error message now.
