### ISSUE TITLE
List View filtering is not working properly

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_monitor#86]
Not Up, Triggered or Breached:
![image](https://user-images.githubusercontent.com/9052188/53027528-0743d680-345d-11e9-847f-d16ecc3c9e6b.png)

Not Up or Triggered:
![image](https://user-images.githubusercontent.com/9052188/53027617-31959400-345d-11e9-9ff1-66443a0bfd8d.png)

These should be the same.

**Comment by cigamit** [comment]
There is a subtle difference between the two status'.  It's simply not reported in the status column yet.

**Comment by TheWitness** [comment]
Unable to reproduce

**Comment by netniV** [comment]
Does it now say breached instead of just down?
