### ISSUE TITLE
Feature: Extra Large Size in Monitor

### ISSUE THREAD

**Issue by KnoAll** [Cacti/plugin_monitor#88]
It would be great to have an Extra Large size in the monitor view. We have this up on 4k screens and large is actually a bit small.

**Comment by netniV** [comment]
Could you send some my way so I can properly test this out for you ?

**Comment by KnoAll** [comment]
How do you mean? A screenshot, or?

**Comment by netniV** [comment]
I was joking about having the same display ;)

**Comment by KnoAll** [comment]
ooooh, sorry! yea, i'll drop something in the mail today!

**Comment by cigamit** [comment]
So, please ship a nice monitor to Texas too ;)

**Comment by KnoAll** [comment]
after doing a pull the plugin is crashing with error 500.

**Comment by KnoAll** [comment]
![image](https://user-images.githubusercontent.com/7632685/53130437-1723ef00-351f-11e9-9585-bee8c3b0d856.png)

**Comment by netniV** [comment]
What error is in you logs?

**Comment by KnoAll** [comment]
Sorry, should have looked/sent that originally....

2019/02/20 15:32:35 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'monitor'
--
2019/02/20 15:32:35 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2019/02/20 15:32:35 - ERROR PHP ERROR in Plugin 'monitor': Uncaught Error: Call to undefined function get_uptime() in /var/www/html/cacti/plugins/monitor/monitor.php:1365 Stack trace: #0 /var/www/html/cacti/plugins/monitor/monitor.php(865): render_host(Array, true, 12) #1 /var/www/html/cacti/plugins/monitor/monitor.php(157): render_default() #2 /var/www/html/cacti/plugins/monitor/monitor.php(131): draw_page() #3 {main} thrown in file: /var/www/html/cacti/plugins/monitor/monitor.php on line: 1365

**Comment by netniV** [comment]
Ah, you need to update to the latest 1.2.2 develop branch of cacti's core.  Monitor is relying on that functionality.

**Comment by KnoAll** [comment]
ah yes, there we go. looks great, thanks!
