### ISSUE TITLE
Cacti Monitor Plugin Ping Threshold Notication

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#9]
There aren't  links to host in raport :(

**Comment by cigamit** [comment]
Be more specific.

**Comment by interduo** [comment]
![mail_thold](https://cloud.githubusercontent.com/assets/17087236/21502343/6a7a2e2a-cc4f-11e6-8667-624ff61955a7.png)

'@Temperatura' is a hostname this should be < a href = https://cactiserver/graphs.php?host_id=123

**Comment by cigamit** [comment]
Resolved, thanks!
