### ISSUE TITLE
Context menu for device options

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_monitor#90]
**Is your feature request related to a problem? Please describe.**
Currently, clicking on a device within monitor will take you to the graphs for that host.  To disable a device, change a threshold, etc, you have to either go back to cacti and search manually for the device, or realise that if you hover over the device, you can get those options which is not obvious

**Describe the solution you'd like**
A context menu should be added that allows navigation to edit the device, view the graphs, view the thresholds, etc.

**Describe alternatives you've considered**
Hovering over the device to get device status information isn't the obvious place to find the links to Edit the Device, View Graphs/Thresohlds. Most users would attempt to right click to find additionally functionality.

**Comment by interduo** [comment]
The context menu could contains also link to:
```
<a href="http://ip">HTTP</a>
<a href="winbox://ip">Winbox</a> 
<a href="ping://ip">Ping</a>
```
It would be very useful! :)

**Comment by cigamit** [comment]
Those are not well know URL scheme's.  Can you please at least register them at iana?  Here is the link:

https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

**Comment by interduo** [comment]
Did You ever use URL Handlers in internet browser?

It could be another other links whitch is registred in IANA - I need to use URL handler with browser to do some actions with it. It doesn't needs to be require in IANA.

For example if I click:
- "ping://" there is running in terminal ping command,
- "mtr://" there is running in terminal mtr command,
- "winbox://" there is running in terminal winbox command.

**Comment by netniV** [comment]
There are unlimited posibilities for unregistered/recognised URL schema's.  Adding the ability for that should be on an separate enhancement request.

**Comment by interduo** [comment]
Is this a plugin case or cacti core case? The URL shema would be good also on devices tab.

**Comment by cigamit** [comment]
The problem is that all browsers are not supporting those schemes.  This is why they should be registered.  Which browser are you using?

**Comment by interduo** [comment]
Firefox and Chromium supports URL handlers, Edge also.
We are using Chrome/Chromium mostly and Firefox.

**Comment by netniV** [comment]
Again, URL handlers are custom made.  Having the ability to specify a custom scheme to appear within monitor is a completely separate enhancement request.  Those schemes and the format of the URL would need to be defined somehow, that is separate to this request and seems to be taking over it.

Please open that as a separate enhancement request and then I can tidy this one back to what it was about.

**Comment by interduo** [comment]
Again, I asked: Is this a monitor plugin thing or cacti core case?
I need to create issue in propper place because the moderator will close my issue if I did It wrong.

**Comment by netniV** [comment]
If there are multiple places in the core that require it, it goes in core.  Otherwise it's the plugin.  There's more chance of a custom URL scheme being applied in Monitor than core though as there are a large number of feature requests for 1.3

**Comment by cigamit** [comment]
I'm going to suggest a text area that will includes json such as the following:

```json
[ { "name" : "Winbox", "url" : "winbox://|hostname|", "icon": "fa fa-cross" } ]
```

What about that?  I guess we could also go with yml, but better use json.  The other approach would be to use a table.

**Comment by interduo** [comment]
`[ { "name" : "Winbox", "url" : "winbox://|hostname|", "icon": "fa fa-cross" } ]`

It would be perfect. The json file should be sufficient. 
There is a need to edit those files one time by few years.

**Comment by TheWitness** [comment]
I did not address the JSON bit for things like Winbox.  I think that @netniV's comments are correct.
