### ISSUE TITLE
Call to undefined function get_uptime($host) error

### ISSUE THREAD

**Issue by mtownsend0773** [Cacti/plugin_monitor#91]
**Describe the bug**
I would get errors in the Cacti log with backtrack to monitor.php line 1365. This line is to collect the up time for a monitored host. However, the get_uptime() function is not defined or created within monitor.php or any of the includes.

I commented lines 1365 and 1742 out and removed the reference to $tis from lines 1367 and 1744 to clear the error. 

Without knowing what get_uptime() was to return I cannot create the function call for get_uptime().

**To Reproduce**
1 install monitor on a new cacti installation
2 enable monitor
3 review the cacti log for error.

**Expected behavior**
I expected to see the system up time for each host that is being monitored

**Screenshots**

**Plugin (plreace complete the following information):**
 - Version: 2.3.5 for Cacti 1.2.0
 - Source: github
 - Identifer: plugin_monitor_develop

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 72.0.3626.119 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by netniV** [comment]
`get_uptime()` is part of Cacti 1.2.2 and also requires THold 1.2.1

As such I've updated monitors requirements in the iNFO file to handle this.
