### ISSUE TITLE
Device Reboot notice should be suppressed on device creation/editing

### ISSUE THREAD

**Issue by netniV** [Cacti/plugin_monitor#93]
**Describe the bug**
When enabling device detection, you can get a spurious notice the device rebooted when in fact it was merely unrecorded previously.

**To Reproduce**
Set "Downed Device Detection" to "Ping Or SNMP Uptime"

**Expected behavior**
On first poll, uptime is identified before reboot detection kicks in.

**Comment by cigamit** [comment]
Resolved.
