### ISSUE TITLE
Filtering devices by name

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#96]
**Is your feature request related to a problem?**
We need filter device by name. The problem is that that if we have too many devices - the results are not much readable.

**Describe the solution you'd like**
We expected filter like in devices form.

**Additional context**
This could be additional input field just before:
`<span class="ui-selectmenu-text">All Monitored</span>`

**Comment by cigamit** [comment]
Okay, this is done now.  Thanks for the Idea

**Comment by interduo** [comment]
Is there a possibility to remove "Refresh button" and do some "live searching" ?

**Comment by netniV** [comment]
The refresh button is there to allow people to refresh before the timeout, and to set multiple criteria without hitting the database (which on large installations would be slow with live filtering).

**Comment by interduo** [comment]
Now I understand the intention of the autor ;).

**Comment by interduo** [comment]
This is not working as expected - the enter key in this field isn't working. You need to click "Refresh".
@netniV could You confirm this bug?

**Comment by netniV** [comment]
Open that as a separate issue since the original enhancement here has actually been resolved.  Your new issue is to do with a separate bit of functionality and is likely not been considered as previously monitor only had drop downs.
