### ISSUE TITLE
Filtering devices by site

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#97]
**Is your feature request related to a problem?**
We need filter device by site names. The problem is that that if we have too many devices - the results are not much readable and then not as useful as expected.

**Describe the solution you'd like**
We expected filter like in devices form.

**Additional context**
This could be additional input field just before:
<span class="ui-selectmenu-text">All Monitored</span> or some where in filtering bar.

**Comment by netniV** [comment]
At first I was going to say that sites were implemented, but that's only for grouping.  PArt of me feels that the monitoring page is supposed to be a simple page for displaying the state of those servers monitored, not becoming a replica of the devices page.  Adding more and more filters takes up room on the page.

**Comment by netniV** [comment]
I think if we haven't already we should make the filter table collapsible.

**Comment by interduo** [comment]
The filterbar is collapsable. We have much room for filters - the screens are more wide than height. There is a plently of space, this isn't a problem.

So what for to group if You cannot use that group in filtering?:)

**Comment by netniV** [comment]
Please don't forget, the site is responsive so it will also work on Mobiles/Tablet devices.  Just because a desktop has a very nice monitor with large amounts of space, doesn't mean a mobile device does.

That said, the filter table is now collapsible which was part of the updates done recently (hence I forgot about it).

Adding the extra filter shouldn't be too much hassle.

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/53806586-3c642480-3f45-11e9-83f2-0f747aa224f9.png)

**Comment by netniV** [comment]
An example of a mobile view:
![image](https://user-images.githubusercontent.com/9052188/53806665-7503fe00-3f45-11e9-8da9-6c66a5156740.png)

**Comment by cigamit** [comment]
We will be handling the responsive filters in 1.3.  So, I'll close this now.
