### ISSUE TITLE
i18n headers bleeding into output of website

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#99]
**Describe the bug**
Remove debug information

**To Reproduce**
1. Go to 'monitor.php'

**Expected behavior**
Clean monitor.php without debug info like 
"Project-Id-Version: Report-Msgid-Bugs-To: POT-Creation-Date: 2019-01-27 12:06-0500 PO-Revision-Date: 2018-12-30 16:00-0500 Last-Translator: Language-Team: Language: pl_PL MIME-Version: 1.0 Content-Type: text/plain; charset=UTF-8 Content-Transfer-Encoding: 8bit Plural-Forms:"

**Screenshots**
![chrome](https://user-images.githubusercontent.com/17087236/53881614-69cbd380-4014-11e9-9f80-5ef0b438610f.png)

**Plugin (please complete the following information):**
 - Version: [origin/develop]
 - Source: [github]
 - Identifer: [8dbc777ad65f15518df7c5f741e51254b1545eb4]

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [Chromium]
 - Version [71.0.3578.98]

**Comment by interduo** [comment]
It's also breaking responsive view.

**Comment by interduo** [comment]
And I think the browser scrollers (up-down) also disappears by this.

**Comment by netniV** [comment]
That is NOT debug information.  That is i18n language details and it almost looks like it's the headers to one of them.

**Comment by interduo** [comment]
We don't need them here so for me is a debug information ;-)

Also there is doubled:
```
All Monitored Devices, and All Criticalities
Remember to first select eligible Devices to be Monitored from the Devices page!
```

In monitor.php

**Comment by netniV** [comment]
That last one is a separate issue.  The i18n is strange because you shouldn't see that text which appears from the top of the POT/MO files.

**Comment by interduo** [comment]
> That last one is a separate issue. The i18n is strange because you shouldn't see that text which appears from the top of the POT/MO files.

So I made separate issue.
https://github.com/Cacti/plugin_monitor/issues/102

**Comment by cigamit** [comment]
Yea, what language?

**Comment by cigamit** [comment]
Okay, it's polish and not our issue.  @interduo, you have some configuration issue locally.

**Comment by interduo** [comment]
I don't think so. I have synchronized aplication with git (develop branch). 


I think that It could be connected with this issue - translations are messed up,

I checked twice settings - there are all set to English. In global and users menu.

![translation](https://user-images.githubusercontent.com/17087236/53941894-a4d41280-40b9-11e9-9ebd-a713c164d25e.png)

**Comment by cigamit** [comment]
Run the following command:

`cd /var/www/html/cacti`
`find . -name \*.mo -exec file {} \; | grep -v "message catalog"`

My guess is that you get a few hits.  Delete them.  Not our issue, though it might be a packaging issue.  Let us know what you find.  Basically, you have some po files in the LC_MESSAGES directories, which is not correct.

**Comment by interduo** [comment]
Is this a good command? Empty result.

**Comment by cigamit** [comment]
Take off the trailing grep and you should get results.

**Comment by interduo** [comment]
```
root@cacti:/var/www/html/cacti/plugins/monitor# find . -name \*.mo -exec file {} \;
./locales/LC_MESSAGES/es-ES.mo: GNU message catalog (little endian), revision 0.0, 134 messages
./locales/LC_MESSAGES/zh-CN.mo: GNU message catalog (little endian), revision 0.0, 132 messages
```

**Comment by interduo** [comment]
```
root@cacti:/var/www/html/cacti# find . -name \*.mo -exec file {} \;
./locales/LC_MESSAGES/pt-BR.mo: GNU message catalog (little endian), revision 0.0, 673 messages
./locales/LC_MESSAGES/it-IT.mo: GNU message catalog (little endian), revision 0.0, 652 messages
./locales/LC_MESSAGES/de-DE.mo: GNU message catalog (little endian), revision 0.0, 1330 messages
./locales/LC_MESSAGES/nl-NL.mo: GNU message catalog (little endian), revision 0.0, 2702 messages
./locales/LC_MESSAGES/ar-SA.mo: GNU message catalog (little endian), revision 0.0, 324 messages
./locales/LC_MESSAGES/vi-VN.mo: GNU message catalog (little endian), revision 0.0, 553 messages
./locales/LC_MESSAGES/ja-JP.mo: GNU message catalog (little endian), revision 0.0, 746 messages
./locales/LC_MESSAGES/bg-BG.mo: GNU message catalog (little endian), revision 0.0, 474 messages
./locales/LC_MESSAGES/sv-SE.mo: GNU message catalog (little endian), revision 0.0, 587 messages
./locales/LC_MESSAGES/pt-PT.mo: GNU message catalog (little endian), revision 0.0, 486 messages
./locales/LC_MESSAGES/tr-TR.mo: GNU message catalog (little endian), revision 0.0, 632 messages
./locales/LC_MESSAGES/el-GR.mo: GNU message catalog (little endian), revision 0.0, 479 messages
./locales/LC_MESSAGES/zh-CN.mo: GNU message catalog (little endian), revision 0.0, 3645 messages
./locales/LC_MESSAGES/zh-TW.mo: GNU message catalog (little endian), revision 0.0, 654 messages
./locales/LC_MESSAGES/ko-KR.mo: GNU message catalog (little endian), revision 0.0, 524 messages
./locales/LC_MESSAGES/es-ES.mo: GNU message catalog (little endian), revision 0.0, 3800 messages
./locales/LC_MESSAGES/he-IL.mo: GNU message catalog (little endian), revision 0.0, 509 messages
./locales/LC_MESSAGES/hi-IN.mo: GNU message catalog (little endian), revision 0.0, 113 messages
./locales/LC_MESSAGES/pl-PL.mo: GNU message catalog (little endian), revision 0.0, 576 messages
./locales/LC_MESSAGES/fr-FR.mo: GNU message catalog (little endian), revision 0.0, 917 messages
./locales/LC_MESSAGES/ru-RU.mo: GNU message catalog (little endian), revision 0.0, 853 messages
./plugins/thold/locales/LC_MESSAGES/zh-CN.mo: GNU message catalog (little endian), revision 0.0, 489 messages
./plugins/maint/locales/LC_MESSAGES/es-ES.mo: GNU message catalog (little endian), revision 0.0, 86 messages
./plugins/monitor/locales/LC_MESSAGES/es-ES.mo: GNU message catalog (little endian), revision 0.0, 134 messages
./plugins/monitor/locales/LC_MESSAGES/zh-CN.mo: GNU message catalog (little endian), revision 0.0, 132 messages
```

**Comment by interduo** [comment]
I did in localesdir:
`./build_gettext.sh && ./update-pot.sh`

**Comment by interduo** [comment]
This situation exists when You choose "tree view". 

@cigamit could You confirm that this situation doesn't exists when You choose tree view?

**Comment by cigamit** [comment]
Found the issue.  Very odd.

**Comment by interduo** [comment]
Thanks for removing 'gibberish' :D

**Comment by cigamit** [comment]
When is that Polish translation going to be done @interduo ?

**Comment by interduo** [comment]
@cigamit give me the file and brackets to fill and It will be done.

**Comment by netniV** [comment]
It is always the pl-pl.pot files.  There's polish in all plugins/core.

**Comment by cigamit** [comment]
So, basically, in `<path_cacti>/locales/po` there is a file called pl_PL.po.  You need to edit this file.  In there you will find a number of lines that look like the one below:

```shell
#: about.php:29 include/global_arrays.php:2374 lib/html.php:2309
#, fuzzy
msgid "About Cacti"
msgstr "Informacje o kaktusach"
```

What you need to do is for every line in the file that contains "msgid", which is the English words, you need to replace the "msgstr" with the Polish translation.  When you are satisfied with the translation, remove the `#, fuzzy` line as that tells GetText that you are still uncertain of the translation and to not show it in the page.  Google did most all of them but they are still marked #fuzzy as no one has audited them.  So, we need you to clean up the rest.

For the plugins, you need to download poedit, it's freely available for Windows, and create a pl_PL.po file based upon the plugins cacti.pot, and place it in the plugins 'locales/po' directory.  You will find that each plugin has a 'cacti.pot' as well as Cacti itself.

To see your changes in the Cacti UI, there is a build_mo.sh script in each plugin directory.  Simply mark it executable, and run it.  You might have to run a dos2unix on them before hand.

If the plugin changes, and you need to merge new strings into the pl_PL.po from the cacti.pot, you would run the: 

```shell
./build_gettext.sh
```
Then, translate your new strings.

**Comment by interduo** [comment]
It's resolved correctly.
